using System;
using System.Collections.Generic;
using System.Globalization;
using System.Text;

using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace Assimalign.Viu.Compiler.SingleFileComponent;

/// <summary>
/// Renders a <see cref="SingleFileComponentModel"/> into the generated partial class for a <c>.viu</c>
/// component. The output is deterministic and fully statically analyzable (no reflection, no dynamic
/// code generation), so it is trimming- and WASM/NativeAOT-safe. Both seams are filled: the
/// template block's compiled render function ([V01.01.05.05]) is emitted from the model's
/// pre-serialized, frame-based render body, and the <c>@script</c> block's C#
/// ([V01.01.06.03]) is merged verbatim under a <c>#line</c> map so compiler errors and debugger stepping
/// resolve to the <c>.viu</c> source. The script splits into two <c>#line</c>-mapped regions
/// ([V01.01.06.03.01]): leading <c>using</c> directives are hoisted into the file's using region above the
/// namespace, and the remaining members are merged into the class body (see <see cref="ScriptRegions"/>).
/// A template-bearing component derives from <c>ComponentBase</c> and implements <c>IComponent</c>
/// ([SFC-CG-4]). The generated bridge assigns <c>Context</c>, binds declared parameters from
/// <c>ComponentContext.Bindings</c>, and returns the frame-taking renderer. The class stays
/// <c>partial</c>, so a user-authored sibling <c>.cs</c> partial and the merged script otherwise coexist;
/// because the base type is declared here, no other partial declaration may name a different one.
/// </summary>
internal static class SingleFileComponentSourceEmitter
{
    /// <summary>
    /// The fully qualified namespace containing the approved component authoring contracts. The generator
    /// binds these types by name and therefore does not reference the runtime assembly itself.
    /// </summary>
    private const string ComponentsNamespace = "global::Assimalign.Viu.Components";

    /// <summary>Emits the full generated source for <paramref name="model"/>.</summary>
    /// <param name="model">The scaffold to render.</param>
    /// <returns>The generated C# source text.</returns>
    public static string Emit(in SingleFileComponentModel model)
    {
        var builder = new StringBuilder();
        builder.Append("// <auto-generated/>\n#nullable enable\n\n");

        // [V01.01.06.03.01] Hoisted @script using directives. Leading usings (plain, using static, and
        // aliases) are lifted out of the class body into the file's using region above the namespace,
        // under their own #line map so a malformed or unresolved using resolves to the .viu source. The
        // remaining @script members stay in the class body (see AppendScriptSeam). C# permits using /
        // using static / using-alias directives in any order, so authored directives retain their source
        // order without a generator-owned import preamble.
        if (model.IsScriptSetupFirst)
        {
            AppendScriptUsingRegion(builder, model.FilePath, model.ScriptSetup);
            AppendScriptUsingRegion(builder, model.FilePath, model.Script);
        }
        else
        {
            AppendScriptUsingRegion(builder, model.FilePath, model.Script);
            AppendScriptUsingRegion(builder, model.FilePath, model.ScriptSetup);
        }

        var indent = 0;
        var hasNamespace = !string.IsNullOrEmpty(model.Namespace);
        if (hasNamespace)
        {
            builder.Append("namespace ").Append(model.Namespace).Append('\n');
            builder.Append("{\n");
            indent = 1;
        }

        AppendIndent(builder, indent);
        builder.Append("// Generated partial-class scaffold for the \"").Append(model.ClassName)
            .Append("\" single-file component, compiled from\n");
        AppendIndent(builder, indent);
        builder.Append("// \"").Append(model.FileName)
            .Append("\" by the Assimalign.Viu.Syntax source generator ([V01.01.06.02]).\n");
        AppendIndent(builder, indent);
        builder.Append("//\n");
        AppendIndent(builder, indent);
        builder.Append("// Parsed blocks: template=").Append(Present(model.HasTemplate))
            .Append(", @script=").Append(Present(model.HasScript))
            .Append(", style=").Append(Count(model.StyleCount))
            .Append(", custom=").Append(Count(model.CustomBlockCount)).Append(".\n");

        AppendIndent(builder, indent);
        builder.Append("partial class ").Append(model.ClassName);
        if (model.RenderBody is not null)
        {
            // [SFC-CG-4] The base owns only Context storage; the generated partial opts into the
            // authored component contract explicitly. A renderless file remains a plain partial class.
            builder.Append(" : ").Append(ComponentsNamespace).Append(".ComponentBase, ")
                .Append(ComponentsNamespace).Append(".IComponent");
        }

        builder.Append('\n');
        AppendIndent(builder, indent);
        builder.Append("{\n");

        var bodyIndent = indent + 1;
        AppendHotReloadMetadata(builder, bodyIndent, model);
        if (model.HotReloadMetadata is not null)
        {
            builder.Append('\n');
        }

        if (model.RenderBody is { } renderBody)
        {
            // [V01.01.05.05] The compiled template render function. The body was serialized by the
            // template compiler's RenderFunctionEmitter and is already indented for this nesting depth.
            AppendIndent(builder, bodyIndent);
            builder.Append("/// <summary>\n");
            AppendIndent(builder, bodyIndent);
            builder.Append("/// The compiled render function for the component's template block ([V01.01.05.05]) — the\n");
            AppendIndent(builder, bodyIndent);
            builder.Append("/// output of the Viu template compiler for this component's template.\n");
            AppendIndent(builder, bodyIndent);
            builder.Append("/// </summary>\n");
            AppendIndent(builder, bodyIndent);
            builder.Append("private static ").Append(ComponentsNamespace).Append(".VirtualNode? __ViuRender(")
                .Append(model.ClassName).Append(" component, ")
                .Append(ComponentsNamespace).Append(".ComponentRenderFrame frame)\n");
            AppendIndent(builder, bodyIndent);
            builder.Append("{\n");
            builder.Append(renderBody);
            AppendIndent(builder, bodyIndent);
            builder.Append("}\n");

            AppendComponentDefinitionBridge(builder, bodyIndent, model);
        }
        else
        {
            AppendIndent(builder, bodyIndent);
            builder.Append("// [V01.01.05.05] No template block: no render function is emitted for this component.\n");
        }

        builder.Append('\n');

        AppendScriptSeam(builder, bodyIndent, model);

        AppendStyleSeam(builder, bodyIndent, model);

        AppendIndent(builder, indent);
        builder.Append("}\n");

        if (hasNamespace)
        {
            builder.Append("}\n");
        }

        return builder.ToString();
    }

    // [V01.01.06.05]/[SFC-CG-4] Development metadata is emit-time gated. The module initializer
    // registers stable marker type identities with Core; authored components implement no metadata
    // interface. Each marker retains its block hash in a method body, which remains patchable by Hot
    // Reload without reflection or a mutable component-instance cache.
    private static void AppendHotReloadMetadata(
        StringBuilder builder,
        int indent,
        in SingleFileComponentModel model)
    {
        if (model.HotReloadMetadata is not { } metadata)
        {
            return;
        }

        AppendIndent(builder, indent);
        builder.Append("/// <summary>Registers this component's development-time marker identities.</summary>\n");
        AppendIndent(builder, indent);
        builder.Append("[global::System.Runtime.CompilerServices.ModuleInitializer]\n");
        AppendIndent(builder, indent);
        builder.Append("internal static void RegisterViuHotReloadMetadata()\n");
        AppendIndent(builder, indent + 1);
        builder.Append("=> global::Assimalign.Viu.ComponentHotReload.Register(\n");
        AppendIndent(builder, indent + 2);
        builder.Append("typeof(").Append(model.ClassName).Append("),\n");
        AppendIndent(builder, indent + 2);
        builder.Append(Literal(metadata.ComponentIdentifier)).Append(",\n");
        AppendIndent(builder, indent + 2);
        builder.Append("typeof(SingleFileComponentTemplateUpdateMarker),\n");
        AppendIndent(builder, indent + 2);
        builder.Append("typeof(SingleFileComponentScriptUpdateMarker),\n");
        AppendIndent(builder, indent + 2);
        builder.Append("typeof(SingleFileComponentStyleUpdateMarker));\n");

        AppendHotReloadMarker(
            builder,
            indent,
            "SingleFileComponentTemplateUpdateMarker",
            metadata.TemplateContentHash);
        AppendHotReloadMarker(
            builder,
            indent,
            "SingleFileComponentScriptUpdateMarker",
            metadata.ScriptContentHash);
        AppendHotReloadMarker(
            builder,
            indent,
            "SingleFileComponentStyleUpdateMarker",
            metadata.StyleContentHash);

    }

    private static void AppendHotReloadMarker(
        StringBuilder builder,
        int indent,
        string markerName,
        string contentHash)
    {
        builder.Append('\n');
        builder.Append('\n');
        AppendIndent(builder, indent);
        builder.Append("private static class ").Append(markerName).Append('\n');
        AppendIndent(builder, indent);
        builder.Append("{\n");
        AppendIndent(builder, indent + 1);
        builder.Append("internal static void TrackContentRevision()\n");
        AppendIndent(builder, indent + 1);
        builder.Append("{\n");
        AppendIndent(builder, indent + 2);
        builder.Append("global::System.GC.KeepAlive(")
            .Append(Literal(contentHash)).Append(");\n");
        AppendIndent(builder, indent + 1);
        builder.Append("}\n");
        AppendIndent(builder, indent);
        builder.Append("}\n");
    }

    // [SFC-CG-3]/[SFC-CG-4] The generated registration publishes the static contract before
    // activation. Setup assigns Context, binds runtime-resolved values, runs the authored hook, and
    // returns a renderer that receives the mount-owned frame.
    private static void AppendComponentDefinitionBridge(StringBuilder builder, int indent, in SingleFileComponentModel model)
    {
        var displayName = model.ClassName.Length > 0 && model.ClassName[0] == '@'
            ? model.ClassName.Substring(1)
            : model.ClassName;

        builder.Append('\n');
        AppendIndent(builder, indent);
        builder.Append("// [SFC-CG-3]/[SFC-CG-4] Static contract, explicit registration, and setup bridge.\n");

        AppendContract(builder, indent, model, displayName);

        builder.Append('\n');
        AppendIndent(builder, indent);
        builder.Append("/// <summary>The reflection-free registration consumed by the generated assembly catalog.</summary>\n");
        AppendIndent(builder, indent);
        builder.Append("internal static readonly ").Append(ComponentsNamespace)
            .Append(".ComponentRegistration __ViuRegistration = new(\n");
        AppendIndent(builder, indent + 1);
        // Static component tags compile to ComponentReference.ForName, so the generated catalog must
        // publish that same identity. Registering only the CLR type would leave every compiled custom
        // tag unresolved even though its component was present in the assembly.
        builder.Append(ComponentsNamespace).Append(".ComponentReference.ForName(")
            .Append(Literal(displayName)).Append("),\n");
        AppendIndent(builder, indent + 1);
        builder.Append("__ViuContract,\n");
        AppendIndent(builder, indent + 1);
        builder.Append("static services => new ").Append(model.ClassName).Append("());\n");

        AppendLifecycleForwarders(builder, indent, model);

        builder.Append('\n');
        AppendIndent(builder, indent);
        builder.Append("/// <summary>Runs developer-authored synchronous setup after <see cref=\"Context\"/> is assigned.</summary>\n");
        AppendIndent(builder, indent);
        builder.Append("partial void OnSetup();\n");

        builder.Append('\n');
        AppendIndent(builder, indent);
        builder.Append("/// <summary>Initializes this mount and returns its frame-based renderer.</summary>\n");
        AppendIndent(builder, indent);
        builder.Append("/// <param name=\"context\">The runtime-provided context for this mount.</param>\n");
        AppendIndent(builder, indent);
        builder.Append("/// <returns>The render function producing the component's subtree.</returns>\n");
        AppendIndent(builder, indent);
        builder.Append(ComponentsNamespace).Append(".ComponentRenderer ")
            .Append(ComponentsNamespace).Append(".IComponent.Setup(\n");
        AppendIndent(builder, indent + 1);
        builder.Append(ComponentsNamespace).Append(".ComponentContext context)\n");
        AppendIndent(builder, indent);
        builder.Append("{\n");

        AppendIndent(builder, indent + 1);
        builder.Append("Context = context;\n");
        if (model.Declarations.Parameters.Count > 0)
        {
            AppendIndent(builder, indent + 1);
            builder.Append("__ViuBindParameters(context.Bindings);\n");
        }

        AppendIndent(builder, indent + 1);
        builder.Append("OnSetup();\n");
        builder.Append('\n');

        if (model.Declarations.Parameters.Count == 0)
        {
            AppendIndent(builder, indent + 1);
            builder.Append("return frame => __ViuRender(this, frame);\n");
        }
        else
        {
            AppendIndent(builder, indent + 1);
            builder.Append("return frame =>\n");
            AppendIndent(builder, indent + 1);
            builder.Append("{\n");
            AppendIndent(builder, indent + 2);
            builder.Append("__ViuBindParameters(context.Bindings);\n");
            AppendIndent(builder, indent + 2);
            builder.Append("return __ViuRender(this, frame);\n");
            AppendIndent(builder, indent + 1);
            builder.Append("};\n");
        }

        AppendIndent(builder, indent);
        builder.Append("}\n");

        AppendRequiredMemberConstructor(builder, indent, model);
        AppendParameterBinding(builder, indent, model);
        AppendEventEmitters(builder, indent, model);
    }

    private static void AppendContract(
        StringBuilder builder,
        int indent,
        in SingleFileComponentModel model,
        string displayName)
    {
        AppendIndent(builder, indent);
        builder.Append("/// <summary>The immutable component contract read before activation.</summary>\n");
        AppendIndent(builder, indent);
        builder.Append("internal static readonly ").Append(ComponentsNamespace)
            .Append(".ComponentContract __ViuContract = new(\n");
        AppendIndent(builder, indent + 1);
        builder.Append("displayName: ").Append(Literal(displayName)).Append(",\n");
        AppendIndent(builder, indent + 1);
        builder.Append("flags: ").Append(ComponentsNamespace)
            .Append(".ComponentFlags.InheritFallthroughBindings,\n");

        if (model.Declarations.Parameters.Count > 0)
        {
            AppendIndent(builder, indent + 1);
            builder.Append("parameters: new ").Append(ComponentsNamespace)
                .Append(".ComponentParameter[]\n");
            AppendIndent(builder, indent + 1);
            builder.Append("{\n");
            AppendContractParameters(builder, indent + 2, model);
            AppendIndent(builder, indent + 1);
            builder.Append("},\n");
        }

        if (model.Declarations.Events.Count > 0)
        {
            AppendIndent(builder, indent + 1);
            builder.Append("events: new ").Append(ComponentsNamespace).Append(".ComponentEvent[]\n");
            AppendIndent(builder, indent + 1);
            builder.Append("{\n");
            AppendContractEvents(builder, indent + 2, model);
            AppendIndent(builder, indent + 1);
            builder.Append("},\n");
        }

        AppendIndent(builder, indent + 1);
        builder.Append("renderCacheSize: ").Append(Count(model.RenderCacheSize)).Append(");\n");
    }

    private static void AppendContractParameters(
        StringBuilder builder,
        int indent,
        in SingleFileComponentModel model)
    {
        AppendIndent(builder, indent);
        builder.Append("#pragma warning disable CS8639 // typeof erases nullable reference annotations.\n");
        foreach (var parameter in model.Declarations.Parameters)
        {
            AppendIndent(builder, indent);
            builder.Append("new ").Append(ComponentsNamespace).Append(".ComponentParameter(")
                .Append(Literal(parameter.Name));
            if (parameter.IsRequired)
            {
                builder.Append(", isRequired: true");
            }

            builder.Append(", parameterType: typeof(").Append(parameter.TypeText).Append(")),\n");
        }

        AppendIndent(builder, indent);
        builder.Append("#pragma warning restore CS8639\n");
    }

    private static void AppendContractEvents(
        StringBuilder builder,
        int indent,
        in SingleFileComponentModel model)
    {
        foreach (var componentEvent in model.Declarations.Events)
        {
            AppendIndent(builder, indent);
            builder.Append("new ").Append(ComponentsNamespace).Append(".ComponentEvent(")
                .Append(Literal(componentEvent.Name))
                .Append(", static arguments => arguments.Count == ")
                .Append(Count(componentEvent.ArgumentCount))
                .Append("),\n");
        }
    }

    private static void AppendLifecycleForwarders(
        StringBuilder builder,
        int indent,
        in SingleFileComponentModel model)
    {
        foreach (var lifecycleMethod in LifecycleMethods)
        {
            if (HasAuthoredLifecycleOverload(model, lifecycleMethod))
            {
                continue;
            }

            builder.Append('\n');
            AppendIndent(builder, indent);
            builder.Append("/// <summary>Forwards root-level lifecycle registration to this mount's context.</summary>\n");
            AppendIndent(builder, indent);
            builder.Append("protected void ").Append(lifecycleMethod.Name).Append('(')
                .Append(lifecycleMethod.CallbackType).Append(" callback)\n");
            AppendIndent(builder, indent + 1);
            builder.Append("=> global::Assimalign.Viu.Generated.RenderGlue.")
                .Append(lifecycleMethod.Name).Append("(Context!, callback);\n");
        }
    }

    private static bool HasAuthoredLifecycleOverload(
        in SingleFileComponentModel model,
        in LifecycleMethod lifecycleMethod)
        => HasAuthoredLifecycleOverload(model.Script.MemberRegion, lifecycleMethod)
            || HasAuthoredLifecycleOverload(model.ScriptSetup.MemberRegion, lifecycleMethod);

    private static bool HasAuthoredLifecycleOverload(
        string? script,
        in LifecycleMethod lifecycleMethod)
    {
        if (script is null)
        {
            return false;
        }

        var probe = ScriptBlockAnalyzer.ParseProbe(script).Probe;
        if (probe is null)
        {
            return false;
        }

        foreach (var member in probe.Members)
        {
            if (member is not MethodDeclarationSyntax method)
            {
                if (HasAuthoredNonMethodMemberName(member, lifecycleMethod.Name))
                {
                    // [CMP-32] Any authored non-method member owns this name. C# cannot combine it
                    // with generated method overloads, so suppress the complete convenience family.
                    return true;
                }

                continue;
            }

            if (!string.Equals(method.Identifier.Text, lifecycleMethod.Name, StringComparison.Ordinal)
                || method.ParameterList.Parameters.Count != 1)
            {
                continue;
            }

            TypeSyntax? parameterType = method.ParameterList.Parameters[0].Type;
            if (parameterType is not null && lifecycleMethod.Matches(parameterType))
            {
                return true;
            }
        }

        return false;
    }

    private static bool HasAuthoredNonMethodMemberName(MemberDeclarationSyntax member, string name)
    {
        if (member is BaseFieldDeclarationSyntax field)
        {
            foreach (var variable in field.Declaration.Variables)
            {
                if (string.Equals(variable.Identifier.Text, name, StringComparison.Ordinal))
                {
                    return true;
                }
            }

            return false;
        }

        return member switch
        {
            PropertyDeclarationSyntax property =>
                string.Equals(property.Identifier.Text, name, StringComparison.Ordinal),
            EventDeclarationSyntax componentEvent =>
                string.Equals(componentEvent.Identifier.Text, name, StringComparison.Ordinal),
            BaseTypeDeclarationSyntax type =>
                string.Equals(type.Identifier.Text, name, StringComparison.Ordinal),
            DelegateDeclarationSyntax componentDelegate =>
                string.Equals(componentDelegate.Identifier.Text, name, StringComparison.Ordinal),
            _ => false,
        };
    }

    // [CMP-28] A `required` [Parameter] property declares requiredness to VIU, not to C#: the AOT
    // activator is a parameterless `new T()` (no object initializer exists to satisfy the C# rule), so the
    // scaffold supplies a [SetsRequiredMembers] constructor and Viu enforces the requirement itself. The
    // pragma covers the nullable warning that suppression re-enables — the properties are assigned from
    // the component's arguments before setup and before every render, never left at their default.
    private static void AppendRequiredMemberConstructor(
        StringBuilder builder,
        int indent,
        in SingleFileComponentModel model)
    {
        if (!model.Declarations.DeclaresRequiredMember || model.Declarations.DeclaresConstructor)
        {
            return;
        }

        builder.Append('\n');
        AppendIndent(builder, indent);
        builder.Append("/// <summary>\n");
        AppendIndent(builder, indent);
        builder.Append("/// Creates the component for the AOT activator. A <c>required</c> <c>[Parameter]</c> is\n");
        AppendIndent(builder, indent);
        builder.Append("/// satisfied from the parent's arguments ([CMP-28]), not by an object initializer, so this\n");
        AppendIndent(builder, indent);
        builder.Append("/// constructor takes responsibility for the required members.\n");
        AppendIndent(builder, indent);
        builder.Append("/// </summary>\n");
        AppendIndent(builder, indent);
        builder.Append("#pragma warning disable CS8618 // Assigned from component arguments before setup and every render.\n");
        AppendIndent(builder, indent);
        builder.Append("[global::System.Diagnostics.CodeAnalysis.SetsRequiredMembers]\n");
        AppendIndent(builder, indent);
        builder.Append("public ").Append(model.ClassName).Append("()\n");
        AppendIndent(builder, indent);
        builder.Append("{\n");
        AppendIndent(builder, indent);
        builder.Append("}\n");
        AppendIndent(builder, indent);
        builder.Append("#pragma warning restore CS8618\n");
    }

    // [CMP-29] The authored initializer is captured once and restored when Bindings contains no value.
    // The consumer-internal generic glue returns the declared type's default for an incompatible value,
    // preserving the no-coercion contract without reflection.
    private static void AppendParameterBinding(StringBuilder builder, int indent, in SingleFileComponentModel model)
    {
        var parameters = model.Declarations.Parameters;
        if (parameters.Count == 0)
        {
            return;
        }

        builder.Append('\n');
        AppendIndent(builder, indent);
        builder.Append("/// <summary>Whether this instance's parameter defaults have been captured.</summary>\n");
        AppendIndent(builder, indent);
        builder.Append("private bool __ViuParameterDefaultsCaptured;\n");
        foreach (var parameter in parameters)
        {
            builder.Append('\n');
            AppendIndent(builder, indent);
            builder.Append("/// <summary>The captured authored default for the <c>")
                .Append(parameter.Name).Append("</c> parameter.</summary>\n");
            AppendIndent(builder, indent);
            builder.Append("private ").Append(parameter.TypeText).Append(" __ViuParameterDefault")
                .Append(GeneratedMemberSuffix(parameter.PropertyName)).Append(" = default!;\n");
        }

        builder.Append('\n');
        AppendIndent(builder, indent);
        builder.Append("/// <summary>\n");
        AppendIndent(builder, indent);
        builder.Append("/// Assigns the parent's current arguments to this component's <c>[Parameter]</c>\n");
        AppendIndent(builder, indent);
        builder.Append("/// properties ([CMP-29]). Runs once during setup and again at the start of every render\n");
        AppendIndent(builder, indent);
        builder.Append("/// pass, after Core has replaced the context's argument snapshot.\n");
        AppendIndent(builder, indent);
        builder.Append("/// </summary>\n");
        AppendIndent(builder, indent);
        builder.Append("private void __ViuBindParameters(").Append(ComponentsNamespace)
            .Append(".ComponentBindings bindings)\n");
        AppendIndent(builder, indent);
        builder.Append("{\n");
        AppendIndent(builder, indent + 1);
        builder.Append("if (!__ViuParameterDefaultsCaptured)\n");
        AppendIndent(builder, indent + 1);
        builder.Append("{\n");
        foreach (var parameter in parameters)
        {
            AppendIndent(builder, indent + 2);
            builder.Append("__ViuParameterDefault").Append(GeneratedMemberSuffix(parameter.PropertyName))
                .Append(" = ").Append(parameter.PropertyName).Append(";\n");
        }

        AppendIndent(builder, indent + 2);
        builder.Append("__ViuParameterDefaultsCaptured = true;\n");
        AppendIndent(builder, indent + 1);
        builder.Append("}\n");

        foreach (var parameter in parameters)
        {
            builder.Append('\n');
            AppendIndent(builder, indent + 1);
            var suffix = GeneratedMemberSuffix(parameter.PropertyName);
            builder.Append(parameter.PropertyName)
                .Append(" = global::Assimalign.Viu.Generated.RenderGlue.TryReadParameter<")
                .Append(parameter.TypeText).Append(">(bindings.Parameters, ")
                .Append(Literal(parameter.Name)).Append(", out ").Append(parameter.TypeText)
                .Append(" __ViuParameterValue").Append(suffix).Append(")\n");
            AppendIndent(builder, indent + 2);
            builder.Append("? __ViuParameterValue").Append(suffix).Append("\n");
            AppendIndent(builder, indent + 2);
            builder.Append(": __ViuParameterDefault").Append(suffix).Append(";\n");
        }

        AppendIndent(builder, indent);
        builder.Append("}\n");
    }

    // [CMP-30] The implementing half of each attributed `partial void` emit method. The declared event
    // name appears exactly once — in the attribute — so the component's own code calls a strongly typed
    // method instead of repeating a string literal. The payload is materialized explicitly rather than
    // through the params overload, so a single array-typed argument stays ONE emitted argument.
    private static void AppendEventEmitters(StringBuilder builder, int indent, in SingleFileComponentModel model)
    {
        foreach (var componentEvent in model.Declarations.Events)
        {
            builder.Append('\n');
            AppendIndent(builder, indent);
            builder.Append("/// <summary>Emits this component's declared <c>").Append(componentEvent.Name)
                .Append("</c> event to the parent ([CMP-30]).</summary>\n");
            AppendIndent(builder, indent);
            builder.Append(componentEvent.Modifiers).Append(" void ").Append(componentEvent.MethodName)
                .Append(componentEvent.ParameterList).Append('\n');
            AppendIndent(builder, indent + 1);
            builder.Append("=> Context!.Emit(").Append(Literal(componentEvent.Name)).Append(", ");
            if (componentEvent.ArgumentCount == 0)
            {
                builder.Append("global::System.Array.Empty<object?>());\n");
            }
            else
            {
                builder.Append("new object?[] { ").Append(componentEvent.ArgumentList).Append(" });\n");
            }
        }
    }

    // [V01.01.06.03]/[V01.01.06.03.01] The @script member seam. Leading using directives are hoisted
    // above the namespace (see Emit); what remains — the class-body members — is merged into the partial
    // class here under a #line map. A script block that contributes no members (all usings, or empty), or
    // no @script block at all, degrades to a documenting comment. The [V01.01.05.05] render seam above
    // stays a placeholder.
    private static void AppendScriptSeam(StringBuilder builder, int indent, in SingleFileComponentModel model)
    {
        bool emittedOrdinaryScript;
        bool emittedSetupScript;
        if (model.IsScriptSetupFirst)
        {
            emittedSetupScript = AppendScriptMemberRegion(
                builder,
                indent,
                model.FilePath,
                model.ScriptSetup,
                isSetup: true);
            emittedOrdinaryScript = AppendScriptMemberRegion(
                builder,
                indent,
                model.FilePath,
                model.Script,
                isSetup: false);
        }
        else
        {
            emittedOrdinaryScript = AppendScriptMemberRegion(
                builder,
                indent,
                model.FilePath,
                model.Script,
                isSetup: false);
            emittedSetupScript = AppendScriptMemberRegion(
                builder,
                indent,
                model.FilePath,
                model.ScriptSetup,
                isSetup: true);
        }

        if (emittedOrdinaryScript || emittedSetupScript)
        {
            return;
        }

        AppendIndent(builder, indent);
        if (model.HasScript)
        {
            builder.Append("// [V01.01.06.03.01] The script block(s) contribute no class-body members; any leading\n");
            AppendIndent(builder, indent);
            builder.Append("// using directives are hoisted into the file's using region above the namespace.\n");
        }
        else
        {
            builder.Append("// [V01.01.06.03] Script merge seam. This component declares no C# script block, so no\n");
            AppendIndent(builder, indent);
            builder.Append("// body is merged into the partial class.\n");
        }
    }

    private static void AppendScriptUsingRegion(
        StringBuilder builder,
        string filePath,
        in ScriptRegions regions)
    {
        if (regions.UsingRegion is not { } usingRegion)
        {
            return;
        }

        AppendLineMappedRegion(
            builder,
            filePath,
            regions.UsingRegionStartLine,
            regions.UsingRegionStartColumn,
            usingRegion);
        builder.Append('\n');
    }

    private static bool AppendScriptMemberRegion(
        StringBuilder builder,
        int indent,
        string filePath,
        in ScriptRegions regions,
        bool isSetup)
    {
        if (regions.MemberRegion is not { } memberRegion)
        {
            return false;
        }

        AppendIndent(builder, indent);
        if (isSetup)
        {
            builder.Append("// [V01.01.06.09] Merged C# <script setup> block. Its partial-class members are emitted\n");
            AppendIndent(builder, indent);
            builder.Append("// verbatim under #line directives, preserving exact diagnostics and debugger stepping.\n");
        }
        else
        {
            builder.Append("// [V01.01.06.03] Merged @script block. The block's C# is emitted verbatim below, wrapped in\n");
            AppendIndent(builder, indent);
            builder.Append("// #line directives that map every line back to the .viu source, so compiler errors and\n");
            AppendIndent(builder, indent);
            builder.Append("// debugger stepping land in the .viu file rather than this generated file.\n");
        }

        AppendLineMappedRegion(
            builder,
            filePath,
            regions.MemberRegionStartLine,
            regions.MemberRegionStartColumn,
            memberRegion);
        return true;
    }

    // Emits a verbatim @script region flush against column 0 (no scaffold indentation added), wrapped in a
    // #line map. The C# #line directive remaps the LINE of the following text but takes each token's COLUMN
    // verbatim from this generated file. @-block script content and line-split regions begin at column 1;
    // inline tag-block script content (.vue) can begin later, so the first emitted line is padded to the region's source
    // column. Subsequent source lines already begin at column 1. A reported (line, column) therefore lands
    // on the exact component coordinate — the same block-to-file mapping
    // SingleFileComponentDiagnostics composes. The trailing #line default restores this generated file's
    // own line mapping for whatever follows (the namespace or class close). Shared by the hoisted using
    // region (above the namespace) and the merged member region.
    private static void AppendLineMappedRegion(
        StringBuilder builder,
        string filePath,
        int startLine,
        int startColumn,
        string content)
    {
        builder.Append("#line ").Append(startLine.ToString(CultureInfo.InvariantCulture))
            .Append(" \"").Append(filePath).Append("\"\n");
        if (startColumn > 1)
        {
            builder.Append(' ', startColumn - 1);
        }

        builder.Append(content);
        if (content.Length == 0 || content[content.Length - 1] != '\n')
        {
            builder.Append('\n');
        }

        builder.Append("#line default\n");
    }

    // [V01.01.06.04] Style extraction remains a build-time channel. Runtime scoped-CSS identifiers and
    // v-bind application are deliberately absent during the component-model migration; CSS Modules
    // accessors and the extracted text consumed by bundling remain.
    private static void AppendStyleSeam(StringBuilder builder, int indent, in SingleFileComponentModel model)
    {
        if (model.ExtractedStyles is not { } styles)
        {
            AppendIndent(builder, indent);
            builder.Append("// [V01.01.06.04] Style seam. This component declares no style block, so no\n");
            AppendIndent(builder, indent);
            builder.Append("// compiled CSS is emitted.\n");
            return;
        }

        builder.Append('\n');
        AppendIndent(builder, indent);
        builder.Append("// [V01.01.06.04] Compiled style blocks retained for static asset bundling; scoped-CSS\n");
        AppendIndent(builder, indent);
        builder.Append("// runtime application is deferred.\n");

        AppendIndent(builder, indent);
        builder.Append("/// <summary>\n");
        AppendIndent(builder, indent);
        builder.Append("/// The component's compiled CSS extracted for static asset bundling.\n");
        AppendIndent(builder, indent);
        builder.Append("/// The WASM runtime performs no CSS parsing or generation.\n");
        AppendIndent(builder, indent);
        builder.Append("/// </summary>\n");
        AppendIndent(builder, indent);
        if (model.HotReloadMetadata is null)
        {
            builder.Append("internal const string ExtractedStyles = ").Append(Literal(styles)).Append(";\n");
        }
        else
        {
            builder.Append("internal static string ExtractedStyles => ").Append(Literal(styles)).Append(";\n");
        }

        AppendModuleAccessors(builder, indent, model);
    }

    // [V01.01.06.06] The style module accessor seam. Each `module` block's original -> hashed class map is
    // emitted as a nested static class — the compiled form of the template's `$style` object — whose
    // const members carry the declared class names, so a reference to a class that does not exist is a
    // compile error. Blocks that share an accessor (several `module` style blocks, or `module="name"` repeated)
    // merge into one class; a duplicate member is emitted once.
    private static void AppendModuleAccessors(StringBuilder builder, int indent, in SingleFileComponentModel model)
    {
        if (model.ModuleClasses.Count == 0)
        {
            return;
        }

        var accessors = new List<string>();
        var membersByAccessor = new Dictionary<string, List<(string Member, string Hashed)>>(StringComparer.Ordinal);
        var seen = new HashSet<string>(StringComparer.Ordinal);
        foreach (var entry in model.ModuleClasses)
        {
            var member = MemberName(entry.Original);
            if (!seen.Add(entry.Accessor + "." + member))
            {
                continue;
            }

            if (!membersByAccessor.TryGetValue(entry.Accessor, out var members))
            {
                members = new List<(string, string)>();
                membersByAccessor[entry.Accessor] = members;
                accessors.Add(entry.Accessor);
            }

            members.Add((member, entry.Hashed));
        }

        foreach (var accessor in accessors)
        {
            builder.Append('\n');
            AppendIndent(builder, indent);
            builder.Append("/// <summary>\n");
            AppendIndent(builder, indent);
            builder.Append("/// The typed CSS Modules accessor for this component's <c>module</c> style block — the\n");
            AppendIndent(builder, indent);
            builder.Append("/// compiled form of the template's <c>$style</c> object. Each member is the locally-hashed\n");
            AppendIndent(builder, indent);
            builder.Append("/// name of the like-named source class, so a reference to an undeclared class fails to compile.\n");
            AppendIndent(builder, indent);
            builder.Append("/// </summary>\n");
            AppendIndent(builder, indent);
            builder.Append("internal static class ").Append(accessor).Append('\n');
            AppendIndent(builder, indent);
            builder.Append("{\n");
            foreach (var (member, hashed) in membersByAccessor[accessor])
            {
                AppendIndent(builder, indent + 1);
                builder.Append("public const string ").Append(member).Append(" = ").Append(Literal(hashed)).Append(";\n");
            }

            AppendIndent(builder, indent);
            builder.Append("}\n");
        }
    }

    // Turns an authored class name into a valid C# member identifier: non-identifier characters become '_'
    // and a leading digit is prefixed with '_'. Deterministic so the accessor is stable across rebuilds.
    // Internal so the template-compile path ([V01.01.05.04.01]) resolves `$style.<member>` references against
    // the exact same member names this emitter writes as the accessor class's consts.
    internal static string MemberName(string original)
    {
        var builder = new StringBuilder(original.Length);
        foreach (var character in original)
        {
            builder.Append(char.IsLetterOrDigit(character) || character == '_' ? character : '_');
        }

        if (builder.Length == 0)
        {
            return "_";
        }

        if (char.IsDigit(builder[0]))
        {
            builder.Insert(0, '_');
        }

        return builder.ToString();
    }

    private static string GeneratedMemberSuffix(string identifier)
        => identifier.Length > 0 && identifier[0] == '@'
            ? identifier.Substring(1)
            : identifier;

    private static bool MatchesLifecycleCallback(
        TypeSyntax type,
        LifecycleCallbackKind callbackKind)
    {
        SimpleNameSyntax? simpleName = RightmostSimpleName(type);
        if (callbackKind == LifecycleCallbackKind.Action)
        {
            return simpleName is IdentifierNameSyntax identifier
                && string.Equals(identifier.Identifier.Text, "Action", StringComparison.Ordinal);
        }

        if (simpleName is not GenericNameSyntax generic
            || !string.Equals(generic.Identifier.Text, "Func", StringComparison.Ordinal))
        {
            return false;
        }

        var arguments = generic.TypeArgumentList.Arguments;
        return callbackKind switch
        {
            LifecycleCallbackKind.FunctionTask =>
                arguments.Count == 1 && IsSimpleType(arguments[0], "Task"),
            LifecycleCallbackKind.FunctionCancellationTask =>
                arguments.Count == 2
                && IsSimpleType(arguments[0], "CancellationToken")
                && IsSimpleType(arguments[1], "Task"),
            LifecycleCallbackKind.ErrorCaptured =>
                arguments.Count == 4
                && IsSimpleType(arguments[0], "Exception")
                && IsSimpleType(arguments[1], "ComponentContext")
                && IsSimpleType(arguments[2], "string")
                && IsSimpleType(arguments[3], "bool"),
            _ => false,
        };
    }

    private static bool IsSimpleType(TypeSyntax type, string expected)
    {
        if (type is NullableTypeSyntax nullable)
        {
            type = nullable.ElementType;
        }

        SimpleNameSyntax? name = RightmostSimpleName(type);
        if (name is not null)
        {
            return string.Equals(name.Identifier.Text, expected, StringComparison.Ordinal);
        }

        return type is PredefinedTypeSyntax predefined
            && string.Equals(predefined.Keyword.Text, expected, StringComparison.Ordinal);
    }

    private static SimpleNameSyntax? RightmostSimpleName(TypeSyntax type)
        => type switch
        {
            SimpleNameSyntax simpleName => simpleName,
            QualifiedNameSyntax qualified => qualified.Right,
            AliasQualifiedNameSyntax aliasQualified => aliasQualified.Name,
            NullableTypeSyntax nullable => RightmostSimpleName(nullable.ElementType),
            _ => null,
        };

    // A valid C# string literal for arbitrary CSS text (quotes, backslashes, and newlines escaped).
    private static string Literal(string value)
        => Microsoft.CodeAnalysis.CSharp.SymbolDisplay.FormatLiteral(value, quote: true);

    private static string Present(bool present) => present ? "present" : "absent";

    private static string Count(int count) => count.ToString(CultureInfo.InvariantCulture);

    private static void AppendIndent(StringBuilder builder, int levels)
    {
        for (var level = 0; level < levels; level++)
        {
            builder.Append("    ");
        }
    }

    private static readonly LifecycleMethod[] LifecycleMethods =
    {
        new("OnBeforeMount", "global::System.Action", LifecycleCallbackKind.Action),
        new("OnBeforeMount", "global::System.Func<global::System.Threading.Tasks.Task>", LifecycleCallbackKind.FunctionTask),
        new("OnBeforeMount", "global::System.Func<global::System.Threading.CancellationToken, global::System.Threading.Tasks.Task>", LifecycleCallbackKind.FunctionCancellationTask),
        new("OnMounted", "global::System.Action", LifecycleCallbackKind.Action),
        new("OnMounted", "global::System.Func<global::System.Threading.Tasks.Task>", LifecycleCallbackKind.FunctionTask),
        new("OnMounted", "global::System.Func<global::System.Threading.CancellationToken, global::System.Threading.Tasks.Task>", LifecycleCallbackKind.FunctionCancellationTask),
        new("OnBeforeUpdate", "global::System.Action", LifecycleCallbackKind.Action),
        new("OnBeforeUpdate", "global::System.Func<global::System.Threading.Tasks.Task>", LifecycleCallbackKind.FunctionTask),
        new("OnBeforeUpdate", "global::System.Func<global::System.Threading.CancellationToken, global::System.Threading.Tasks.Task>", LifecycleCallbackKind.FunctionCancellationTask),
        new("OnUpdated", "global::System.Action", LifecycleCallbackKind.Action),
        new("OnUpdated", "global::System.Func<global::System.Threading.Tasks.Task>", LifecycleCallbackKind.FunctionTask),
        new("OnUpdated", "global::System.Func<global::System.Threading.CancellationToken, global::System.Threading.Tasks.Task>", LifecycleCallbackKind.FunctionCancellationTask),
        new("OnBeforeUnmount", "global::System.Action", LifecycleCallbackKind.Action),
        new("OnBeforeUnmount", "global::System.Func<global::System.Threading.Tasks.Task>", LifecycleCallbackKind.FunctionTask),
        new("OnBeforeUnmount", "global::System.Func<global::System.Threading.CancellationToken, global::System.Threading.Tasks.Task>", LifecycleCallbackKind.FunctionCancellationTask),
        new("OnUnmounted", "global::System.Action", LifecycleCallbackKind.Action),
        new("OnUnmounted", "global::System.Func<global::System.Threading.Tasks.Task>", LifecycleCallbackKind.FunctionTask),
        new("OnUnmounted", "global::System.Func<global::System.Threading.CancellationToken, global::System.Threading.Tasks.Task>", LifecycleCallbackKind.FunctionCancellationTask),
        new("OnActivated", "global::System.Action", LifecycleCallbackKind.Action),
        new("OnActivated", "global::System.Func<global::System.Threading.Tasks.Task>", LifecycleCallbackKind.FunctionTask),
        new("OnActivated", "global::System.Func<global::System.Threading.CancellationToken, global::System.Threading.Tasks.Task>", LifecycleCallbackKind.FunctionCancellationTask),
        new("OnDeactivated", "global::System.Action", LifecycleCallbackKind.Action),
        new("OnDeactivated", "global::System.Func<global::System.Threading.Tasks.Task>", LifecycleCallbackKind.FunctionTask),
        new("OnDeactivated", "global::System.Func<global::System.Threading.CancellationToken, global::System.Threading.Tasks.Task>", LifecycleCallbackKind.FunctionCancellationTask),
        new("OnServerPrefetch", "global::System.Action", LifecycleCallbackKind.Action),
        new("OnServerPrefetch", "global::System.Func<global::System.Threading.Tasks.Task>", LifecycleCallbackKind.FunctionTask),
        new("OnServerPrefetch", "global::System.Func<global::System.Threading.CancellationToken, global::System.Threading.Tasks.Task>", LifecycleCallbackKind.FunctionCancellationTask),
        new("OnErrorCaptured", "global::System.Func<global::System.Exception, global::Assimalign.Viu.Components.ComponentContext?, string, bool>", LifecycleCallbackKind.ErrorCaptured),
    };

    private readonly struct LifecycleMethod
    {
        internal LifecycleMethod(
            string name,
            string callbackType,
            LifecycleCallbackKind callbackKind)
        {
            Name = name;
            CallbackType = callbackType;
            CallbackKind = callbackKind;
        }

        internal string Name { get; }

        internal string CallbackType { get; }

        private LifecycleCallbackKind CallbackKind { get; }

        internal bool Matches(TypeSyntax type) => MatchesLifecycleCallback(type, CallbackKind);
    }

    private enum LifecycleCallbackKind
    {
        Action,
        FunctionTask,
        FunctionCancellationTask,
        ErrorCaptured,
    }
}
