<Project>
  <Import Project="..\Directory.Build.props" />
  <PropertyGroup>
    <ViuRedesignDirectory>$([MSBuild]::EnsureTrailingSlash('$(MSBuildThisFileDirectory)'))</ViuRedesignDirectory>
    <IsPackable>false</IsPackable>
    <GeneratePackageOnBuild>false</GeneratePackageOnBuild>
    <ViuLanguageServerPublishEnabled>false</ViuLanguageServerPublishEnabled>
    <ViuUseSingleFileComponents>false</ViuUseSingleFileComponents>
    <ViuBundleSingleFileComponentCss>false</ViuBundleSingleFileComponentCss>
    <ViuBundleUtilityCss>false</ViuBundleUtilityCss>
    <ViuCssHotReloadEnabled>false</ViuCssHotReloadEnabled>
  </PropertyGroup>
</Project>
