using System.Linq;

using Microsoft.CodeAnalysis;

using Shouldly;
using Xunit;

namespace Assimalign.Vue.Reactivity.Generators.Tests;

/// <summary>
/// Snapshot, diagnostic, and incremental-cache tests for <see cref="ReactiveGenerator"/>. The
/// snapshot locks the exact emitted code (upstream parity: interception compiled in, no reflection);
/// the incremental test pins that unrelated edits do not re-run generation.
/// </summary>
public sealed class ReactiveGeneratorTests
{
    private const string TodoItemSource = """
        using Assimalign.Vue.Reactivity;
        namespace Demo;
        [Reactive]
        public partial class TodoItem
        {
            public partial string Title { get; set; }
            public partial bool Done { get; set; }
        }
        """;

    [Fact]
    public void Generates_TrackTriggerImplementation_ForDeepReactiveClass()
    {
        // Snapshot lock: the generated getter tracks, the setter triggers only on an
        // EqualityComparer change, the type implements IReactiveObject (raw access, per-property
        // dependency lookup, deep traversal), and a ReactiveReferences bundle plus ToReferences()
        // exposes per-property write-through refs (the toRefs counterpart). Mirrors the hand-written
        // ComponentProperties pattern.
        const string expected =
"""
// <auto-generated/>
#nullable enable

namespace Demo
{
    public partial class TodoItem : global::Assimalign.Vue.Reactivity.IReactiveObject
    {
        private global::Assimalign.Vue.Reactivity.Dependency __TitleDependency = new global::Assimalign.Vue.Reactivity.Dependency();
        private string __TitleValue = default!;

        public partial string Title
        {
            get
            {
                this.__TitleDependency.Track();
                return this.__TitleValue;
            }
            set
            {
                if (!global::System.Collections.Generic.EqualityComparer<string>.Default.Equals(this.__TitleValue, value))
                {
                    this.__TitleValue = value;
                    this.__TitleDependency.Trigger();
                }
            }
        }

        private global::Assimalign.Vue.Reactivity.Dependency __DoneDependency = new global::Assimalign.Vue.Reactivity.Dependency();
        private bool __DoneValue = default!;

        public partial bool Done
        {
            get
            {
                this.__DoneDependency.Track();
                return this.__DoneValue;
            }
            set
            {
                if (!global::System.Collections.Generic.EqualityComparer<bool>.Default.Equals(this.__DoneValue, value))
                {
                    this.__DoneValue = value;
                    this.__DoneDependency.Trigger();
                }
            }
        }

        object global::Assimalign.Vue.Reactivity.IReactiveObject.ToRaw() => this;

        global::Assimalign.Vue.Reactivity.Dependency? global::Assimalign.Vue.Reactivity.IReactiveObject.GetDependency(string propertyName)
        {
            switch (propertyName)
            {
                case "Title":
                    return this.__TitleDependency;
                case "Done":
                    return this.__DoneDependency;
                default:
                    return null;
            }
        }

        void global::Assimalign.Vue.Reactivity.IReactiveTraversable.Traverse(global::Assimalign.Vue.Reactivity.ReactiveTraversal traversal)
        {
            traversal.Visit(this.Title);
            _ = this.Done;
        }

        public readonly struct ReactiveReferences
        {
            internal ReactiveReferences(TodoItem source)
            {
                this.Title = global::Assimalign.Vue.Reactivity.Reactive.ToRef<string>(() => source.Title, value => source.Title = value);
                this.Done = global::Assimalign.Vue.Reactivity.Reactive.ToRef<bool>(() => source.Done, value => source.Done = value);
            }

            public global::Assimalign.Vue.Reactivity.IReference<string> Title { get; }

            public global::Assimalign.Vue.Reactivity.IReference<bool> Done { get; }
        }

        public ReactiveReferences ToReferences() => new ReactiveReferences(this);

        public readonly struct RawValues
        {
            private readonly TodoItem _owner;

            internal RawValues(TodoItem owner)
            {
                this._owner = owner;
            }

            public string Title
            {
                get => this._owner.__TitleValue;
                set => this._owner.__TitleValue = value;
            }

            public bool Done
            {
                get => this._owner.__DoneValue;
                set => this._owner.__DoneValue = value;
            }
        }

        public RawValues ToRawValues() => new RawValues(this);
    }
}
""";

        var outcome = GeneratorTestHarness.Run(TodoItemSource);

        outcome.Diagnostics.ShouldBeEmpty();
        Normalize(GeneratorTestHarness.GeneratedSource(outcome, "TodoItem.Reactive.g.cs"))
            .ShouldBe(Normalize(expected));
    }

    [Fact]
    public void ShallowReactive_ReadsRootPropertiesWithoutRecursing_AndNestsPartialContainers()
    {
        const string source = """
            using Assimalign.Vue.Reactivity;
            namespace Demo;
            public partial class Outer
            {
                [ShallowReactive]
                internal partial class Inner
                {
                    public partial int Count { get; set; }
                }
            }
            """;

        var generated = GeneratorTestHarness.GeneratedSource(GeneratorTestHarness.Run(source), "Inner.Reactive.g.cs");

        // Containing type re-declared partial, shallow traversal reads the property (tracks) without
        // descending, so no Visit call is emitted.
        generated.ShouldContain("partial class Outer");
        generated.ShouldContain("internal partial class Inner : global::Assimalign.Vue.Reactivity.IReactiveObject");
        generated.ShouldContain("_ = this.Count;");
        generated.ShouldNotContain("traversal.Visit(");
    }

    [Fact]
    public void ReadonlyReactive_SetterWarnsAndDoesNotTrigger_ButReadsStillTrack()
    {
        const string source = """
            using Assimalign.Vue.Reactivity;
            namespace Demo;
            [Reactive(Readonly = true)]
            public partial class Frozen { public partial string Name { get; set; } }
            """;

        var generated = GeneratorTestHarness.GeneratedSource(GeneratorTestHarness.Run(source), "Frozen.Reactive.g.cs");

        generated.ShouldContain("this.__NameDependency.Track();"); // reads still track
        generated.ShouldContain("[Vue warn] Set operation on key \\\"Name\\\" failed: target is readonly.");
        generated.ShouldNotContain(".Trigger();"); // readonly setter does not trigger
    }

    [Fact]
    public void ReadonlyReactive_ImplementsIReadonlyReactiveMarker_ForIsReadonly()
    {
        // The readonly variant implements IReadonlyReactive (IsReadonly => true) so Reactive.IsReadonly()
        // reports a source-generated readonly object — the port of readonly()'s IS_READONLY flag.
        const string source = """
            using Assimalign.Vue.Reactivity;
            namespace Demo;
            [Reactive(Readonly = true)]
            public partial class Frozen { public partial string Name { get; set; } }
            """;

        var generated = GeneratorTestHarness.GeneratedSource(GeneratorTestHarness.Run(source), "Frozen.Reactive.g.cs");

        generated.ShouldContain(", global::Assimalign.Vue.Reactivity.IReadonlyReactive");
        generated.ShouldContain("bool global::Assimalign.Vue.Reactivity.IReadonlyReactive.IsReadonly => true;");
    }

    [Theory]
    [InlineData("[Reactive] public class NotPartial { public int Value { get; set; } }", "VUER1001")]
    [InlineData("[Reactive] public static partial class Statics { }", "VUER1002")]
    [InlineData("[Reactive] public partial class InitOnly { public partial string Name { get; init; } }", "VUER1003")]
    public void ReportsDiagnostic_ForMisuse(string declaration, string expectedId)
    {
        var source = "using Assimalign.Vue.Reactivity; namespace Demo { " + declaration + " }";

        var outcome = GeneratorTestHarness.Run(source);

        outcome.Diagnostics.Select(diagnostic => diagnostic.Id).ShouldContain(expectedId);
    }

    [Fact]
    public void ReportsConflictingAttributes_Once_WhenBothReactiveAndShallowReactivePresent()
    {
        const string source = """
            using Assimalign.Vue.Reactivity;
            namespace Demo;
            [Reactive]
            [ShallowReactive]
            public partial class Both { public partial int Value { get; set; } }
            """;

        var outcome = GeneratorTestHarness.Run(source);

        outcome.Diagnostics.Count(diagnostic => diagnostic.Id == "VUER1004").ShouldBe(1);
        // Conflict blocks generation entirely.
        outcome.Sources.ShouldBeEmpty();
    }

    [Fact]
    public void UnrelatedEdit_DoesNotReRunGeneration()
    {
        // Incremental cache contract: adding an unrelated file must leave the reactive model step
        // Cached/Unchanged (Roslyn incremental-generator cookbook).
        var driver = GeneratorTestHarness.CreateDriver();
        var compilation = GeneratorTestHarness.CreateCompilation(TodoItemSource);

        driver = driver.RunGenerators(compilation);
        var withUnrelated = compilation.AddSyntaxTrees(
            GeneratorTestHarness.Parse("namespace Other { internal sealed class Unrelated { public int Value; } }"));
        driver = driver.RunGenerators(withUnrelated);

        var steps = driver.GetRunResult().Results[0].TrackedSteps[ReactiveGenerator.DeepModelTrackingName];
        steps.SelectMany(step => step.Outputs)
            .Select(output => output.Reason)
            .ShouldAllBe(reason => reason == IncrementalStepRunReason.Cached || reason == IncrementalStepRunReason.Unchanged);
    }

    private static string Normalize(string text) => text.Replace("\r\n", "\n").TrimEnd() + "\n";
}
