<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>$(TargetFrameworkForLibraries)</TargetFramework>
        <IsPackable>false</IsPackable>
    </PropertyGroup>
    <ItemGroup>
        <ViuPackageReference Include="Microsoft.NET.Test.Sdk" />
        <ViuPackageReference Include="Microsoft.Build.Framework" IncludeRuntimeAssets="true" />
        <ViuPackageReference Include="Microsoft.Build.Utilities.Core" IncludeRuntimeAssets="true" />
        <ViuPackageReference Include="xunit" />
        <ViuPackageReference Include="xunit.runner.visualstudio" />
        <ViuPackageReference Include="Shouldly" />
    </ItemGroup>
    <ItemGroup>
        <ViuProjectReference Include="Assimalign.Viu.Sdk.Browser.Tasks" />
    </ItemGroup>
</Project>
