using System.Collections.Immutable;
using System.Linq;

using Microsoft.CodeAnalysis;

using Shouldly;
using Xunit;

// The test namespace is nested under Assimalign.Vue.Syntax, so the base cluster's DiagnosticSeverity is
// ambient and shadows Roslyn's; alias the Roslyn enum the reported diagnostics carry.
using RoslynDiagnosticSeverity = Microsoft.CodeAnalysis.DiagnosticSeverity;

namespace Assimalign.Vue.Syntax.Generators.Tests;

/// <summary>
/// Snapshot, diagnostic, and incremental-cache tests for <see cref="SingleFileComponentGenerator"/>.
/// The snapshot locks the emitted partial-class scaffold and its two clearly-marked seams
/// ([V01.01.05.05] render, [V01.01.06.03] script merge); the diagnostic tests pin that both the
/// <c>.viu</c> block container and the dispatched <c>@template</c> parse (the registration seam) surface
/// as Roslyn diagnostics on the <c>.viu</c> file; the cache tests pin that untouched input reuses cached
/// outputs and a structural edit regenerates.
/// </summary>
public sealed class SingleFileComponentGeneratorTests
{
    private const string ProjectDirectory = "C:/proj";
    private const string RootNamespace = "Demo";

    private const string CounterSource =
        "@template {\n" +
        "    <div>{{ message }}</div>\n" +
        "}\n" +
        "\n" +
        "@script {\n" +
        "    public string Message = \"Hello\";\n" +
        "}\n" +
        "\n" +
        "@style scoped {\n" +
        "    .box { color: red; }\n" +
        "}\n";

    [Fact]
    public void Generates_ScaffoldPartialClass_ForWellFormedComponent()
    {
        // Snapshot lock: a well-formed .viu produces a deterministic partial-class shell whose header
        // reflects the composed parse (template + script + one style) and whose body carries the two
        // downstream seams. No render body or merged @script C# is emitted here — those are
        // [V01.01.05.05] and [V01.01.06.03].
        const string expected =
"""
// <auto-generated/>
#nullable enable

namespace Demo
{
    // Generated partial-class scaffold for the "Counter" single-file component, compiled from
    // "Counter.viu" by the Assimalign.Vue.Syntax source generator ([V01.01.06.02]).
    //
    // Parsed blocks: @template=present, @script=present, @style=1, custom=0.
    partial class Counter
    {
        // [V01.01.05.05] Render function placeholder. The compiled @template render body is emitted
        // here once template code generation lands; the scaffold emits no render output yet.

        // [V01.01.06.03] Script merge seam. The @script block's C# is merged into this partial class
        // (with #line mapping) once script analysis lands; the scaffold emits no @script body yet.
    }
}
""";

        var outcome = GeneratorTestHarness.Run($"{ProjectDirectory}/Counter.viu", CounterSource, RootNamespace, ProjectDirectory);

        outcome.Diagnostics.ShouldBeEmpty();
        Normalize(GeneratorTestHarness.GeneratedSource(outcome, "Counter.SingleFileComponent.g.cs"))
            .ShouldBe(Normalize(expected));
    }

    [Fact]
    public void DerivesNamespaceFromSubfolder_AndPathQualifiedHintName()
    {
        // The namespace composes RootNamespace with the file's directory segments and the hint name is
        // path-qualified, so two same-named .viu files in different folders never collide.
        var outcome = GeneratorTestHarness.Run($"{ProjectDirectory}/Components/Counter.viu", CounterSource, RootNamespace, ProjectDirectory);

        var generated = GeneratorTestHarness.GeneratedSource(outcome, "Components.Counter.SingleFileComponent.g.cs");
        generated.ShouldContain("namespace Demo.Components");
        generated.ShouldContain("partial class Counter");
    }

    [Fact]
    public void MalformedComponent_SurfacesContainerDiagnostic_OnViuFile()
    {
        // A stray top-level line is StrayTopLevelContent in the .viu block container; it maps to the
        // VUECS1001 error located on the .viu file, and the scaffold is still produced (recoverable).
        const string source =
            "@template {\n" +
            "    <div>ok</div>\n" +
            "}\n" +
            "this is stray top-level content\n";

        var outcome = GeneratorTestHarness.Run($"{ProjectDirectory}/Counter.viu", source, RootNamespace, ProjectDirectory);

        var diagnostic = outcome.Diagnostics.ShouldHaveSingleItem();
        diagnostic.Id.ShouldBe("VUECS1001");
        diagnostic.Severity.ShouldBe(RoslynDiagnosticSeverity.Error);
        diagnostic.Location.GetLineSpan().Path.ShouldBe($"{ProjectDirectory}/Counter.viu");
        // Recoverable: the scaffold is emitted even though the file has an error.
        outcome.Sources.ShouldNotBeEmpty();
    }

    [Fact]
    public void MalformedTemplate_SurfacesTemplateDiagnostic_ViaRegistrationSeam()
    {
        // The @template block is dispatched to the registered TemplateSyntaxParser (the composition
        // root's registration seam). An unterminated interpolation is XMissingInterpolationEnd upstream;
        // it maps to the VUECS1101 template error on the .viu file, proving the seam actually parses the
        // block content (the .viu container parser never would on its own).
        const string source =
            "@template {\n" +
            "    {{ message\n" +
            "}\n";

        var outcome = GeneratorTestHarness.Run($"{ProjectDirectory}/Counter.viu", source, RootNamespace, ProjectDirectory);

        var diagnostic = outcome.Diagnostics.ShouldHaveSingleItem();
        diagnostic.Id.ShouldBe("VUECS1101");
        diagnostic.Location.GetLineSpan().Path.ShouldBe($"{ProjectDirectory}/Counter.viu");
    }

    [Fact]
    public void IdenticalInput_AcrossTwoRuns_ReusesCachedOutputs()
    {
        // Incremental cache contract: running the same driver again over unchanged input leaves the
        // model step Cached/Unchanged (Roslyn incremental-generator cookbook).
        var file = new InMemoryAdditionalText($"{ProjectDirectory}/Counter.viu", CounterSource);
        var compilation = GeneratorTestHarness.CreateCompilation();
        var driver = GeneratorTestHarness.CreateDriver(
            ImmutableArray.Create<AdditionalText>(file), RootNamespace, ProjectDirectory);

        driver = driver.RunGenerators(compilation);
        driver = driver.RunGenerators(compilation);

        ModelStepReasons(driver).ShouldAllBe(
            reason => reason == IncrementalStepRunReason.Cached || reason == IncrementalStepRunReason.Unchanged);
    }

    [Fact]
    public void UnrelatedCompilationEdit_DoesNotReRunGeneration()
    {
        // The pipeline depends only on .viu additional files and two build properties, never the
        // compilation, so adding an unrelated C# tree leaves the model step Cached/Unchanged.
        var file = new InMemoryAdditionalText($"{ProjectDirectory}/Counter.viu", CounterSource);
        var compilation = GeneratorTestHarness.CreateCompilation();
        var driver = GeneratorTestHarness.CreateDriver(
            ImmutableArray.Create<AdditionalText>(file), RootNamespace, ProjectDirectory);

        driver = driver.RunGenerators(compilation);
        var withUnrelated = compilation.AddSyntaxTrees(
            GeneratorTestHarness.Parse("namespace Other { internal sealed class Unrelated { public int Value; } }"));
        driver = driver.RunGenerators(withUnrelated);

        ModelStepReasons(driver).ShouldAllBe(
            reason => reason == IncrementalStepRunReason.Cached || reason == IncrementalStepRunReason.Unchanged);
    }

    [Fact]
    public void EditedInput_RegeneratesModel()
    {
        // A structural edit (removing the @script block) changes the model, so the model step re-runs
        // and the regenerated scaffold reflects the change.
        const string edited =
            "@template {\n" +
            "    <div>{{ message }}</div>\n" +
            "}\n" +
            "\n" +
            "@style scoped {\n" +
            "    .box { color: red; }\n" +
            "}\n";

        var file = new InMemoryAdditionalText($"{ProjectDirectory}/Counter.viu", CounterSource);
        var compilation = GeneratorTestHarness.CreateCompilation();
        var driver = GeneratorTestHarness.CreateDriver(
            ImmutableArray.Create<AdditionalText>(file), RootNamespace, ProjectDirectory);

        driver = driver.RunGenerators(compilation);
        driver = driver.ReplaceAdditionalText(file, new InMemoryAdditionalText($"{ProjectDirectory}/Counter.viu", edited));
        driver = driver.RunGenerators(compilation);

        ModelStepReasons(driver).ShouldContain(
            reason => reason == IncrementalStepRunReason.Modified || reason == IncrementalStepRunReason.New);

        var result = driver.GetRunResult().Results[0];
        var generated = result.GeneratedSources
            .Single(source => source.HintName.EndsWith("Counter.SingleFileComponent.g.cs"))
            .SourceText.ToString();
        generated.ShouldContain("@script=absent");
    }

    private static ImmutableArray<IncrementalStepRunReason> ModelStepReasons(GeneratorDriver driver)
        => driver.GetRunResult().Results[0]
            .TrackedSteps[SingleFileComponentGenerator.ModelTrackingName]
            .SelectMany(step => step.Outputs)
            .Select(output => output.Reason)
            .ToImmutableArray();

    private static string Normalize(string text) => text.Replace("\r\n", "\n").TrimEnd() + "\n";
}
