using System.Collections.Immutable;
using System.Linq;

using Microsoft.CodeAnalysis;

using Shouldly;
using Xunit;

// The test namespace is nested under Assimalign.Vue.Syntax, so the base cluster's DiagnosticSeverity is
// ambient and shadows Roslyn's; alias the Roslyn enum the reported diagnostics carry.
using RoslynDiagnosticSeverity = Microsoft.CodeAnalysis.DiagnosticSeverity;

namespace Assimalign.Vue.Syntax.Generators.Tests;

/// <summary>
/// Snapshot, diagnostic, and incremental-cache tests for <see cref="SingleFileComponentGenerator"/>.
/// The snapshot locks the emitted partial-class scaffold and its two clearly-marked seams
/// ([V01.01.05.05] render, [V01.01.06.03] script merge); the diagnostic tests pin that both the
/// <c>.viu</c> block container and the dispatched <c>@template</c> parse (the registration seam) surface
/// as Roslyn diagnostics on the <c>.viu</c> file; the cache tests pin that untouched input reuses cached
/// outputs and a structural edit regenerates.
/// </summary>
public sealed class SingleFileComponentGeneratorTests
{
    private const string ProjectDirectory = "C:/proj";
    private const string RootNamespace = "Demo";

    private const string CounterSource =
        "@template {\n" +
        "    <div>{{ message }}</div>\n" +
        "}\n" +
        "\n" +
        "@script {\n" +
        "    public string Message = \"Hello\";\n" +
        "}\n" +
        "\n" +
        "@style scoped {\n" +
        "    .box { color: red; }\n" +
        "}\n";

    [Fact]
    public void Generates_ScaffoldPartialClass_ForWellFormedComponent()
    {
        // Snapshot lock: a well-formed .viu produces a deterministic partial-class shell whose header
        // reflects the composed parse (template + script + one style). The render body is still a seam
        // placeholder ([V01.01.05.05]); the @script block ([V01.01.06.03]) is merged verbatim into the
        // partial class under a #line map anchored at the .viu content line (6), flush against column 0 so
        // the mapped column matches the source, with #line default restoring the generated file afterward.
        const string expected =
"""
// <auto-generated/>
#nullable enable

namespace Demo
{
    // Generated partial-class scaffold for the "Counter" single-file component, compiled from
    // "Counter.viu" by the Assimalign.Vue.Syntax source generator ([V01.01.06.02]).
    //
    // Parsed blocks: @template=present, @script=present, @style=1, custom=0.
    partial class Counter
    {
        // [V01.01.05.05] Render function placeholder. The compiled @template render body is emitted
        // here once template code generation lands; the scaffold emits no render output yet.

        // [V01.01.06.03] Merged @script block. The block's C# is emitted verbatim below, wrapped in
        // #line directives that map every line back to the .viu source, so compiler errors and
        // debugger stepping land in the .viu file rather than this generated file.
#line 6 "C:/proj/Counter.viu"
    public string Message = "Hello";
#line default
    }
}
""";

        var outcome = GeneratorTestHarness.Run($"{ProjectDirectory}/Counter.viu", CounterSource, RootNamespace, ProjectDirectory);

        outcome.Diagnostics.ShouldBeEmpty();
        Normalize(GeneratorTestHarness.GeneratedSource(outcome, "Counter.SingleFileComponent.g.cs"))
            .ShouldBe(Normalize(expected));
    }

    [Fact]
    public void DerivesNamespaceFromSubfolder_AndPathQualifiedHintName()
    {
        // The namespace composes RootNamespace with the file's directory segments and the hint name is
        // path-qualified, so two same-named .viu files in different folders never collide.
        var outcome = GeneratorTestHarness.Run($"{ProjectDirectory}/Components/Counter.viu", CounterSource, RootNamespace, ProjectDirectory);

        var generated = GeneratorTestHarness.GeneratedSource(outcome, "Components.Counter.SingleFileComponent.g.cs");
        generated.ShouldContain("namespace Demo.Components");
        generated.ShouldContain("partial class Counter");
    }

    [Fact]
    public void MalformedComponent_SurfacesContainerDiagnostic_OnViuFile()
    {
        // A stray top-level line is StrayTopLevelContent in the .viu block container; it maps to the
        // VUECS1001 error located on the .viu file, and the scaffold is still produced (recoverable).
        const string source =
            "@template {\n" +
            "    <div>ok</div>\n" +
            "}\n" +
            "this is stray top-level content\n";

        var outcome = GeneratorTestHarness.Run($"{ProjectDirectory}/Counter.viu", source, RootNamespace, ProjectDirectory);

        var diagnostic = outcome.Diagnostics.ShouldHaveSingleItem();
        diagnostic.Id.ShouldBe("VUECS1001");
        diagnostic.Severity.ShouldBe(RoslynDiagnosticSeverity.Error);
        diagnostic.Location.GetLineSpan().Path.ShouldBe($"{ProjectDirectory}/Counter.viu");
        // Recoverable: the scaffold is emitted even though the file has an error.
        outcome.Sources.ShouldNotBeEmpty();
    }

    [Fact]
    public void MalformedTemplate_SurfacesTemplateDiagnostic_ViaRegistrationSeam()
    {
        // The @template block is dispatched to the registered TemplateSyntaxParser (the composition
        // root's registration seam). An unterminated interpolation is XMissingInterpolationEnd upstream;
        // it maps to the VUECS1101 template error on the .viu file, proving the seam actually parses the
        // block content (the .viu container parser never would on its own).
        const string source =
            "@template {\n" +
            "    {{ message\n" +
            "}\n";

        var outcome = GeneratorTestHarness.Run($"{ProjectDirectory}/Counter.viu", source, RootNamespace, ProjectDirectory);

        var diagnostic = outcome.Diagnostics.ShouldHaveSingleItem();
        diagnostic.Id.ShouldBe("VUECS1101");
        diagnostic.Location.GetLineSpan().Path.ShouldBe($"{ProjectDirectory}/Counter.viu");
    }

    [Fact]
    public void IdenticalInput_AcrossTwoRuns_ReusesCachedOutputs()
    {
        // Incremental cache contract: running the same driver again over unchanged input leaves the
        // model step Cached - strictly Cached, because Unchanged means the step RE-EXECUTED and merely produced an equal output, the exact regression the caching contract must catch.
        var file = new InMemoryAdditionalText($"{ProjectDirectory}/Counter.viu", CounterSource);
        var compilation = GeneratorTestHarness.CreateCompilation();
        var driver = GeneratorTestHarness.CreateDriver(
            ImmutableArray.Create<AdditionalText>(file), RootNamespace, ProjectDirectory);

        driver = driver.RunGenerators(compilation);
        driver = driver.RunGenerators(compilation);

        ModelStepReasons(driver).ShouldAllBe(
            reason => reason == IncrementalStepRunReason.Cached);
    }

    [Fact]
    public void UnrelatedCompilationEdit_DoesNotReRunGeneration()
    {
        // The pipeline depends only on .viu additional files and two build properties, never the
        // compilation, so adding an unrelated C# tree leaves the model step strictly Cached.
        var file = new InMemoryAdditionalText($"{ProjectDirectory}/Counter.viu", CounterSource);
        var compilation = GeneratorTestHarness.CreateCompilation();
        var driver = GeneratorTestHarness.CreateDriver(
            ImmutableArray.Create<AdditionalText>(file), RootNamespace, ProjectDirectory);

        driver = driver.RunGenerators(compilation);
        var withUnrelated = compilation.AddSyntaxTrees(
            GeneratorTestHarness.Parse("namespace Other { internal sealed class Unrelated { public int Value; } }"));
        driver = driver.RunGenerators(withUnrelated);

        ModelStepReasons(driver).ShouldAllBe(
            reason => reason == IncrementalStepRunReason.Cached);
    }

    [Fact]
    public void EditedInput_RegeneratesModel()
    {
        // A structural edit (removing the @script block) changes the model, so the model step re-runs
        // and the regenerated scaffold reflects the change.
        const string edited =
            "@template {\n" +
            "    <div>{{ message }}</div>\n" +
            "}\n" +
            "\n" +
            "@style scoped {\n" +
            "    .box { color: red; }\n" +
            "}\n";

        var file = new InMemoryAdditionalText($"{ProjectDirectory}/Counter.viu", CounterSource);
        var compilation = GeneratorTestHarness.CreateCompilation();
        var driver = GeneratorTestHarness.CreateDriver(
            ImmutableArray.Create<AdditionalText>(file), RootNamespace, ProjectDirectory);

        driver = driver.RunGenerators(compilation);
        driver = driver.ReplaceAdditionalText(file, new InMemoryAdditionalText($"{ProjectDirectory}/Counter.viu", edited));
        driver = driver.RunGenerators(compilation);

        ModelStepReasons(driver).ShouldContain(
            reason => reason == IncrementalStepRunReason.Modified || reason == IncrementalStepRunReason.New);

        var result = driver.GetRunResult().Results[0];
        var generated = result.GeneratedSources
            .Single(source => source.HintName.EndsWith("Counter.SingleFileComponent.g.cs"))
            .SourceText.ToString();
        generated.ShouldContain("@script=absent");
    }

    private static ImmutableArray<IncrementalStepRunReason> ModelStepReasons(GeneratorDriver driver)
        => driver.GetRunResult().Results[0]
            .TrackedSteps[SingleFileComponentGenerator.ModelTrackingName]
            .SelectMany(step => step.Outputs)
            .Select(output => output.Reason)
            .ToImmutableArray();

    private static string Normalize(string text) => text.Replace("\r\n", "\n").TrimEnd() + "\n";

    [Fact]
    public void TemplateDiagnostic_ComposesBlockPositionIntoFileCoordinates()
    {
        // The block-to-file coordinate mapping: the @template content starts on file line 2, and the
        // unterminated interpolation sits on content line 2, so the reported (zero-based) position is
        // file line 2 (= one-based line 3, the "{{ message" line) at column 0 — pinning the
        // Compose() arithmetic, not just the location path.
        const string source =
            "@template {\n" +
            "<b>\n" +
            "{{ message\n" +
            "</b>\n" +
            "}\n";

        var outcome = GeneratorTestHarness.Run($"{ProjectDirectory}/Counter.viu", source, RootNamespace, ProjectDirectory);

        // The unterminated interpolation swallows to EOF, so the unclosed <b> is also reported —
        // both template diagnostics, each composed onto its own .viu file line.
        outcome.Diagnostics.Count().ShouldBe(2);
        var interpolation = outcome.Diagnostics.Single(
            candidate => candidate.GetMessage().Contains("Interpolation end sign"));
        interpolation.Id.ShouldBe("VUECS1101");
        // The per-language catalog code rides on the message (CompilerErrorCode.MissingInterpolationEnd = 25).
        interpolation.GetMessage().ShouldContain("(template compiler code 25)");
        var span = interpolation.Location.GetLineSpan();
        span.Path.ShouldBe($"{ProjectDirectory}/Counter.viu");
        span.StartLinePosition.Line.ShouldBe(2);
        span.StartLinePosition.Character.ShouldBe(0);

        var missingEndTag = outcome.Diagnostics.Single(
            candidate => candidate.GetMessage().Contains("missing end tag"));
        missingEndTag.Location.GetLineSpan().StartLinePosition.Line.ShouldBe(1);
    }

    [Fact]
    public void HintNames_OfCollidingSources_AreDisambiguated()
    {
        // Roslyn's AddSource throws on duplicate hint names and the exception kills the whole generator
        // run, so names that sanitize to the same identifier (and files whose location is unknown) get
        // a stable path-hash suffix — unique by construction.
        var dashed = SingleFileComponentNameResolver.Resolve($"{ProjectDirectory}/Foo-Bar.viu", ProjectDirectory, RootNamespace);
        var underscored = SingleFileComponentNameResolver.Resolve($"{ProjectDirectory}/Foo_Bar.viu", ProjectDirectory, RootNamespace);
        dashed.ClassName.ShouldBe("Foo_Bar");
        underscored.ClassName.ShouldBe("Foo_Bar");
        dashed.HintName.ShouldNotBe(underscored.HintName);

        var outside = SingleFileComponentNameResolver.Resolve("/elsewhere/Counter.viu", ProjectDirectory, RootNamespace);
        var inside = SingleFileComponentNameResolver.Resolve($"{ProjectDirectory}/Counter.viu", ProjectDirectory, RootNamespace);
        outside.HintName.ShouldNotBe(inside.HintName);

        // The disambiguator is deterministic — the same path always yields the same hint (the
        // incremental-caching contract).
        SingleFileComponentNameResolver.Resolve("/elsewhere/Counter.viu", ProjectDirectory, RootNamespace)
            .HintName.ShouldBe(outside.HintName);
    }

    [Fact]
    public void GeneratedIdentifiers_EscapeCSharpKeywords()
    {
        // "class.viu" must emit a legal identifier: the class (and any keyword directory segment)
        // gets the verbatim-identifier prefix.
        var resolved = SingleFileComponentNameResolver.Resolve($"{ProjectDirectory}/class.viu", ProjectDirectory, RootNamespace);
        resolved.ClassName.ShouldBe("@class");
        resolved.HintName.ShouldBe("class.SingleFileComponent.g.cs");
    }
}
