<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>$(TargetFrameworkForLibraries)</TargetFramework>
        <OutputType>Exe</OutputType>
        <UseAppHost>false</UseAppHost>
        <IsPackable>false</IsPackable>
        <IsAotCompatible>true</IsAotCompatible>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
        <GenerateDependencyFile>true</GenerateDependencyFile>
        <OutDir>$(ViuOutputPathForSdk)\$(NETCoreSdkVersion)\sdks\Assimalign.Viu.Sdk.Browser\RunHost\</OutDir>
    </PropertyGroup>
    <ItemGroup>
        <FrameworkReference Include="Microsoft.AspNetCore.App" />
    </ItemGroup>
</Project>
