<Project ToolsVersion="14.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
    <Import Sdk="Microsoft.NET.Sdk" Project="Sdk.targets" />
    <Import Project="..\Targets\Assimalign.Viu.Generators.Syntax.targets"
            Condition="Exists('..\Targets\Assimalign.Viu.Generators.Syntax.targets')" />
    <Import Project="..\Targets\Assimalign.Viu.Sdk.ServerRendering.targets"
            Condition="Exists('..\Targets\Assimalign.Viu.Sdk.ServerRendering.targets')" />
    <Import Project="..\Targets\Assimalign.Viu.Sdk.ComponentStyles.targets"
            Condition="Exists('..\Targets\Assimalign.Viu.Sdk.ComponentStyles.targets')" />
    <Import Project="..\Targets\Assimalign.Viu.Sdk.RuntimeInspection.targets"
            Condition="Exists('..\Targets\Assimalign.Viu.Sdk.RuntimeInspection.targets')" />
</Project>
