using System.Text;

namespace Assimalign.Viu.Generators.Reactivity;

/// <summary>
/// Renders a <see cref="ReactiveClassModel"/> into the partial-class implementation the generator
/// adds: the build-time interception layer that replaces the object proxy Viu deliberately does not
/// have. Every emitted member is fully qualified (no <c>using</c>s), nullable-annotated, and free of
/// reflection so the output is
/// trim/AOT-safe. The per-property getter/setter fast path calls
/// <c>Dependency.Track()</c>/<c>Trigger()</c> directly on a sealed field — no interface dispatch —
/// mirroring the hand-written pattern in the core.s <c>ComponentProperties</c>.
/// </summary>
internal static class ReactiveSourceEmitter
{
    private const string DependencyType = "global::Assimalign.Viu.Reactivity.Dependency";
    private const string ReactiveObjectType = "global::Assimalign.Viu.Reactivity.IReactiveObject";
    private const string ReferenceType = "global::Assimalign.Viu.Reactivity.IReactiveReference";
    private const string ReactiveFacadeType = "global::Assimalign.Viu.Reactivity.Reactive";
    private const string TraversableType = "global::Assimalign.Viu.Reactivity.IReactiveTraversable";
    private const string TraversalType = "global::Assimalign.Viu.Reactivity.ReactiveTraversal";
    private const string EqualityComparerType = "global::System.Collections.Generic.EqualityComparer";

    /// <summary>Emits the full generated source for <paramref name="model"/>.</summary>
    /// <param name="model">The class to implement.</param>
    /// <returns>The generated C# source text.</returns>
    public static string Emit(in ReactiveClassModel model)
    {
        var builder = new StringBuilder();
        builder.Append("// <auto-generated/>\n#nullable enable\n\n");

        var indent = 0;
        var hasNamespace = !string.IsNullOrEmpty(model.Namespace);
        if (hasNamespace)
        {
            builder.Append("namespace ").Append(model.Namespace).Append('\n');
            builder.Append("{\n");
            indent = 1;
        }

        foreach (var container in model.ContainingTypes)
        {
            AppendIndent(builder, indent);
            builder.Append("partial ").Append(container.Keyword).Append(' ')
                .Append(container.Name).Append(container.TypeParameterList).Append('\n');
            AppendIndent(builder, indent);
            builder.Append("{\n");
            indent++;
        }

        AppendIndent(builder, indent);
        builder.Append(model.AccessibilityKeyword).Append("partial class ")
            .Append(model.TypeName).Append(model.TypeParameterList)
            .Append(" : ").Append(ReactiveObjectType);
        builder.Append('\n');
        AppendIndent(builder, indent);
        builder.Append("{\n");

        var bodyIndent = indent + 1;
        EmitProperties(builder, model, bodyIndent);
        EmitDependencyLookup(builder, model, bodyIndent);
        EmitTraversal(builder, model, bodyIndent);
        EmitReadOnlyMarker(builder, model, bodyIndent);
        EmitReferences(builder, model, bodyIndent);
        EmitRawView(builder, model, bodyIndent);

        AppendIndent(builder, indent);
        builder.Append("}\n");

        for (var level = 0; level < model.ContainingTypes.Count; level++)
        {
            indent--;
            AppendIndent(builder, indent);
            builder.Append("}\n");
        }

        if (hasNamespace)
        {
            builder.Append("}\n");
        }

        return builder.ToString();
    }

    private static void EmitProperties(StringBuilder builder, in ReactiveClassModel model, int indent)
    {
        foreach (var property in model.Properties)
        {
            AppendIndent(builder, indent);
            builder.Append("private ").Append(DependencyType).Append(' ')
                .Append(property.DependencyFieldName).Append(" = new ").Append(DependencyType).Append("();\n");

            AppendIndent(builder, indent);
            builder.Append("private ").Append(property.TypeFullName).Append(' ')
                .Append(property.ValueFieldName).Append(" = default!;\n\n");

            AppendIndent(builder, indent);
            builder.Append(property.AccessibilityKeyword).Append("partial ")
                .Append(property.TypeFullName).Append(' ').Append(property.Name).Append('\n');
            AppendIndent(builder, indent);
            builder.Append("{\n");

            AppendIndent(builder, indent + 1);
            builder.Append("get\n");
            AppendIndent(builder, indent + 1);
            builder.Append("{\n");
            AppendIndent(builder, indent + 2);
            builder.Append("this.").Append(property.DependencyFieldName).Append(".Track();\n");
            AppendIndent(builder, indent + 2);
            builder.Append("return this.").Append(property.ValueFieldName).Append(";\n");
            AppendIndent(builder, indent + 1);
            builder.Append("}\n");

            AppendIndent(builder, indent + 1);
            builder.Append(property.SetterModifier).Append("set\n");
            AppendIndent(builder, indent + 1);
            builder.Append("{\n");
            if (model.ReadOnly)
            {
                AppendIndent(builder, indent + 2);
                builder.Append("global::System.Diagnostics.Debug.WriteLine(\"[Viu warn] Set operation on key \\\"")
                    .Append(property.Name).Append("\\\" failed: target is read-only.\");\n");
            }
            else
            {
                AppendIndent(builder, indent + 2);
                builder.Append("if (!").Append(EqualityComparerType).Append('<').Append(property.TypeFullName)
                    .Append(">.Default.Equals(this.").Append(property.ValueFieldName).Append(", value))\n");
                AppendIndent(builder, indent + 2);
                builder.Append("{\n");
                AppendIndent(builder, indent + 3);
                builder.Append("this.").Append(property.ValueFieldName).Append(" = value;\n");
                AppendIndent(builder, indent + 3);
                builder.Append("this.").Append(property.DependencyFieldName).Append(".Trigger();\n");
                AppendIndent(builder, indent + 2);
                builder.Append("}\n");
            }
            AppendIndent(builder, indent + 1);
            builder.Append("}\n");

            AppendIndent(builder, indent);
            builder.Append("}\n\n");
        }
    }

    private static void EmitDependencyLookup(StringBuilder builder, in ReactiveClassModel model, int indent)
    {
        AppendIndent(builder, indent);
        builder.Append(DependencyType).Append("? ").Append(ReactiveObjectType)
            .Append(".GetDependency(string propertyName)\n");
        AppendIndent(builder, indent);
        builder.Append("{\n");
        AppendIndent(builder, indent + 1);
        builder.Append("switch (propertyName)\n");
        AppendIndent(builder, indent + 1);
        builder.Append("{\n");
        foreach (var property in model.Properties)
        {
            AppendIndent(builder, indent + 2);
            builder.Append("case \"").Append(property.Name).Append("\":\n");
            AppendIndent(builder, indent + 3);
            builder.Append("return this.").Append(property.DependencyFieldName).Append(";\n");
        }
        AppendIndent(builder, indent + 2);
        builder.Append("default:\n");
        AppendIndent(builder, indent + 3);
        builder.Append("return null;\n");
        AppendIndent(builder, indent + 1);
        builder.Append("}\n");
        AppendIndent(builder, indent);
        builder.Append("}\n\n");
    }

    private static void EmitTraversal(StringBuilder builder, in ReactiveClassModel model, int indent)
    {
        AppendIndent(builder, indent);
        builder.Append("void ").Append(TraversableType).Append(".Traverse(").Append(TraversalType)
            .Append(" traversal)\n");
        AppendIndent(builder, indent);
        builder.Append("{\n");
        foreach (var property in model.Properties)
        {
            AppendIndent(builder, indent + 1);
            if (model.Shallow || property.IsValueType)
            {
                // Shallow (root-only) or a value-type leaf: read the property to track it, no descent.
                builder.Append("_ = this.").Append(property.Name).Append(";\n");
            }
            else
            {
                // Deep: read (track) and recurse into nested reactive members.
                builder.Append("traversal.Visit(this.").Append(property.Name).Append(");\n");
            }
        }
        AppendIndent(builder, indent);
        builder.Append("}\n");
    }

    private static void EmitReadOnlyMarker(StringBuilder builder, in ReactiveClassModel model, int indent)
    {
        if (!model.ReadOnly)
        {
            // A mutable reactive object uses the default IReactiveObject.IsReadOnly => false.
            return;
        }

        // The readonly marker Reactive.IsReadOnly() observes: a readonly variant overrides the
        // IReactiveObject default-interface member to report true. It is emitted as a compiled
        // member rather than carried in run-time state because there is no proxy to hold a flag.
        builder.Append('\n');
        AppendIndent(builder, indent);
        builder.Append("bool ").Append(ReactiveObjectType).Append(".IsReadOnly => true;\n");
    }

    private static void EmitReferences(StringBuilder builder, in ReactiveClassModel model, int indent)
    {
        if (model.Properties.Count == 0)
        {
            return;
        }

        var sourceType = model.TypeName + model.TypeParameterList;

        // A typed bundle of per-property references, each write-through-linked to this object: every
        // reference reads and writes its property through Reactive.ToRef, so tracking and triggering
        // still route through that property's own dependency and the bundle never becomes a stale
        // snapshot. Destructuring a reactive object therefore keeps reactivity, which a plain
        // property copy would lose. Emitted only when there is at least one reactive property.
        builder.Append('\n');
        AppendIndent(builder, indent);
        builder.Append("public readonly struct ReactiveReferences\n");
        AppendIndent(builder, indent);
        builder.Append("{\n");

        AppendIndent(builder, indent + 1);
        builder.Append("internal ReactiveReferences(").Append(sourceType).Append(" source)\n");
        AppendIndent(builder, indent + 1);
        builder.Append("{\n");
        foreach (var property in model.Properties)
        {
            AppendIndent(builder, indent + 2);
            builder.Append("this.").Append(property.Name).Append(" = ").Append(ReactiveFacadeType)
                .Append(".ToRef<").Append(property.TypeFullName).Append(">(() => source.").Append(property.Name)
                .Append(", value => source.").Append(property.Name).Append(" = value);\n");
        }
        AppendIndent(builder, indent + 1);
        builder.Append("}\n");

        foreach (var property in model.Properties)
        {
            builder.Append('\n');
            AppendIndent(builder, indent + 1);
            builder.Append("public ").Append(ReferenceType).Append('<').Append(property.TypeFullName)
                .Append("> ").Append(property.Name).Append(" { get; }\n");
        }

        AppendIndent(builder, indent);
        builder.Append("}\n");

        builder.Append('\n');
        AppendIndent(builder, indent);
        builder.Append("public ReactiveReferences ToReferences() => new ReactiveReferences(this);\n");
    }

    private static void EmitRawView(StringBuilder builder, in ReactiveClassModel model, int indent)
    {
        if (model.Properties.Count == 0)
        {
            return;
        }

        var sourceType = model.TypeName + model.TypeParameterList;

        // The untracked escape hatch ToRawValues() surfaces a view straight over the raw value
        // fields, where reads do not track and writes do not trigger. Bulk work that would otherwise
        // notify once per assignment goes through it. Emitted for readonly variants too — a readonly
        // variant restricts the reactive surface, not access to the underlying mutable target, so
        // ToRawValues() on one still yields a writable view. As a nested type it reaches the private
        // backing fields without reflection.
        builder.Append('\n');
        AppendIndent(builder, indent);
        builder.Append("public readonly struct RawValues\n");
        AppendIndent(builder, indent);
        builder.Append("{\n");

        AppendIndent(builder, indent + 1);
        builder.Append("private readonly ").Append(sourceType).Append(" _owner;\n");

        builder.Append('\n');
        AppendIndent(builder, indent + 1);
        builder.Append("internal RawValues(").Append(sourceType).Append(" owner)\n");
        AppendIndent(builder, indent + 1);
        builder.Append("{\n");
        AppendIndent(builder, indent + 2);
        builder.Append("this._owner = owner;\n");
        AppendIndent(builder, indent + 1);
        builder.Append("}\n");

        foreach (var property in model.Properties)
        {
            builder.Append('\n');
            AppendIndent(builder, indent + 1);
            builder.Append("public ").Append(property.TypeFullName).Append(' ').Append(property.Name).Append('\n');
            AppendIndent(builder, indent + 1);
            builder.Append("{\n");
            AppendIndent(builder, indent + 2);
            builder.Append("get => this._owner.__").Append(property.Name).Append("Value;\n");
            AppendIndent(builder, indent + 2);
            builder.Append("set => this._owner.__").Append(property.Name).Append("Value = value;\n");
            AppendIndent(builder, indent + 1);
            builder.Append("}\n");
        }

        AppendIndent(builder, indent);
        builder.Append("}\n");

        builder.Append('\n');
        AppendIndent(builder, indent);
        builder.Append("public RawValues ToRawValues() => new RawValues(this);\n");
    }

    private static void AppendIndent(StringBuilder builder, int levels)
    {
        for (var level = 0; level < levels; level++)
        {
            builder.Append("    ");
        }
    }
}
