<Project Sdk="Assimalign.Viu.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <PackageId>PackagedVueComponentConsumer</PackageId>
    <PackageVersion>$(PackagedVueConsumerVersion)</PackageVersion>
    <ViuAppFrameworkVersion>$(ViuConsumerVersion)</ViuAppFrameworkVersion>
  </PropertyGroup>
</Project>
