<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>$(TargetFrameworkForLibraries)</TargetFramework>
    <IsAotCompatible>true</IsAotCompatible>
  </PropertyGroup>
  <ItemGroup>
    <ViuAnalyzerReference Include="Assimalign.Viu.Generators.Reactivity" />
  </ItemGroup>
</Project>
