using System;
using System.Collections.Generic;
using System.Globalization;
using System.Text;

namespace Assimalign.Viu.Syntax.Generators;

/// <summary>
/// Renders a <see cref="SingleFileComponentModel"/> into the generated partial class for a <c>.viu</c>
/// component. The output is deterministic and fully statically analyzable (no reflection, no dynamic
/// code generation), so it is trimming- and WASM/NativeAOT-safe. Both seams are filled: the
/// <c>@template</c> block's compiled render function ([V01.01.05.05]) is emitted from the model's
/// pre-serialized render body — helper names bind <b>by name</b> to the runtime render-helper surface
/// through the file-level <c>using static</c> (the generator never references the runtime assembly; the
/// name/signature contract is documented in
/// <c>libraries/Assimalign.Viu.Syntax.Templates/docs/DESIGN.md</c>) — and the <c>@script</c> block's C#
/// ([V01.01.06.03]) is merged verbatim under a <c>#line</c> map so compiler errors and debugger stepping
/// resolve to the <c>.viu</c> source. The script splits into two <c>#line</c>-mapped regions
/// ([V01.01.06.03.01]): leading <c>using</c> directives are hoisted into the file's using region above the
/// namespace, and the remaining members are merged into the class body (see <see cref="ScriptRegions"/>).
/// Beyond the reserved render members (<c>Render</c>,
/// <c>RenderCacheSize</c>), the scaffold emits no members of its own and the class stays
/// <c>partial</c>, so a user-authored sibling <c>.cs</c> partial and the merged script coexist without
/// collision.
/// </summary>
internal static class SingleFileComponentSourceEmitter
{
    /// <summary>
    /// The fully qualified runtime render-helper surface the emitted render body binds against — the C#
    /// analogue of upstream's function-mode <c>const { ... } = _Vue</c> helper import. The type ships
    /// with the runtime block/vnode helpers ([V01.01.05.02] and follow-ups); the generator only ever
    /// names it.
    /// </summary>
    private const string RenderHelperSurface = "global::Assimalign.Viu.RuntimeCore.RenderHelpers";

    /// <summary>
    /// The fully qualified DOM render-helper surface the emitted render body binds the DOM directive/modifier
    /// helpers against (<c>_vShow</c>, the <c>_vModel*</c> directives, <c>_withModifiers</c>/<c>_withKeys</c>,
    /// <c>_Transition</c>/<c>_TransitionGroup</c>) — the DOM sibling of <see cref="RenderHelperSurface"/>. It
    /// is emitted alongside the runtime-core import so a <c>.viu</c> using DOM directives compiles end to end;
    /// the DOM surface ships with <c>Assimalign.Viu.RuntimeDom</c> ([V01.01.04.09]) and the generator only ever
    /// names it. A browser <c>.viu</c> always has RuntimeDom available (it is the DOM renderer), so both
    /// imports are unconditional whenever a render body is present.
    /// </summary>
    private const string DomRenderHelperSurface = "global::Assimalign.Viu.RuntimeDom.DomRenderHelpers";

    /// <summary>Emits the full generated source for <paramref name="model"/>.</summary>
    /// <param name="model">The scaffold to render.</param>
    /// <returns>The generated C# source text.</returns>
    public static string Emit(in SingleFileComponentModel model)
    {
        var builder = new StringBuilder();
        builder.Append("// <auto-generated/>\n#nullable enable\n\n");

        if (model.RenderBody is not null)
        {
            // The by-name binding site for every emitted helper invocation (_openBlock,
            // _createElementBlock, _toDisplayString, ...): file-level static imports, mirroring
            // upstream's aliased helper preamble. Two surfaces: the platform-agnostic runtime-core helpers
            // and the DOM directive/modifier helpers (_vShow, _vModel*, _withModifiers/_withKeys,
            // _Transition/_TransitionGroup — [V01.01.04.09]), so a .viu using DOM directives binds by name
            // against both.
            builder.Append("using static ").Append(RenderHelperSurface).Append(";\n");
            builder.Append("using static ").Append(DomRenderHelperSurface).Append(";\n\n");
        }

        // [V01.01.06.03.01] Hoisted @script using directives. Leading usings (plain, using static, and
        // aliases) are lifted out of the class body into the file's using region above the namespace,
        // under their own #line map so a malformed or unresolved using resolves to the .viu source. The
        // remaining @script members stay in the class body (see AppendScriptSeam). C# permits using /
        // using static / using-alias directives in any order, so these follow the render-helper preamble
        // without reordering it.
        if (model.Script.UsingRegion is { } usingRegion)
        {
            AppendLineMappedRegion(builder, model.FilePath, model.Script.UsingRegionStartLine, usingRegion);
            builder.Append('\n');
        }

        var indent = 0;
        var hasNamespace = !string.IsNullOrEmpty(model.Namespace);
        if (hasNamespace)
        {
            builder.Append("namespace ").Append(model.Namespace).Append('\n');
            builder.Append("{\n");
            indent = 1;
        }

        AppendIndent(builder, indent);
        builder.Append("// Generated partial-class scaffold for the \"").Append(model.ClassName)
            .Append("\" single-file component, compiled from\n");
        AppendIndent(builder, indent);
        builder.Append("// \"").Append(model.FileName)
            .Append("\" by the Assimalign.Viu.Syntax source generator ([V01.01.06.02]).\n");
        AppendIndent(builder, indent);
        builder.Append("//\n");
        AppendIndent(builder, indent);
        builder.Append("// Parsed blocks: @template=").Append(Present(model.HasTemplate))
            .Append(", @script=").Append(Present(model.HasScript))
            .Append(", @style=").Append(Count(model.StyleCount))
            .Append(", custom=").Append(Count(model.CustomBlockCount)).Append(".\n");

        AppendIndent(builder, indent);
        builder.Append("partial class ").Append(model.ClassName).Append('\n');
        AppendIndent(builder, indent);
        builder.Append("{\n");

        var bodyIndent = indent + 1;
        if (model.RenderBody is { } renderBody)
        {
            // [V01.01.05.05] The compiled @template render function. The body was serialized by the
            // template compiler's RenderFunctionEmitter (the Vue 3.5 codegen.ts analogue) and is
            // already indented for this nesting depth.
            AppendIndent(builder, bodyIndent);
            builder.Append("/// <summary>\n");
            AppendIndent(builder, bodyIndent);
            builder.Append("/// The number of render cache slots (<c>v-once</c> subtrees and cached handlers) the\n");
            AppendIndent(builder, bodyIndent);
            builder.Append("/// <see cref=\"Render\"/> function uses; the runtime allocates <c>_cache</c> with this length.\n");
            AppendIndent(builder, bodyIndent);
            builder.Append("/// </summary>\n");
            AppendIndent(builder, bodyIndent);
            builder.Append("internal const int RenderCacheSize = ").Append(Count(model.RenderCacheSize)).Append(";\n");
            builder.Append('\n');
            AppendIndent(builder, bodyIndent);
            builder.Append("/// <summary>\n");
            AppendIndent(builder, bodyIndent);
            builder.Append("/// The compiled render function for the <c>@template</c> block ([V01.01.05.05]) — the C#\n");
            AppendIndent(builder, bodyIndent);
            builder.Append("/// analogue of the component's compiled <c>render</c> in Vue 3.5 (vuejs/core\n");
            AppendIndent(builder, bodyIndent);
            builder.Append("/// packages/compiler-core/src/codegen.ts). The runtime normalizes the returned value.\n");
            AppendIndent(builder, bodyIndent);
            builder.Append("/// </summary>\n");
            AppendIndent(builder, bodyIndent);
            builder.Append("internal static object? Render(").Append(model.ClassName).Append(" _ctx, object?[] _cache)\n");
            AppendIndent(builder, bodyIndent);
            builder.Append("{\n");
            builder.Append(renderBody);
            AppendIndent(builder, bodyIndent);
            builder.Append("}\n");
        }
        else
        {
            AppendIndent(builder, bodyIndent);
            builder.Append("// [V01.01.05.05] No @template block: no render function is emitted for this component.\n");
        }

        builder.Append('\n');

        AppendScriptSeam(builder, bodyIndent, model);

        AppendStyleSeam(builder, bodyIndent, model);

        AppendIndent(builder, indent);
        builder.Append("}\n");

        if (hasNamespace)
        {
            builder.Append("}\n");
        }

        return builder.ToString();
    }

    // [V01.01.06.03]/[V01.01.06.03.01] The @script member seam. Leading using directives are hoisted
    // above the namespace (see Emit); what remains — the class-body members — is merged into the partial
    // class here under a #line map. A script block that contributes no members (all usings, or empty), or
    // no @script block at all, degrades to a documenting comment. The [V01.01.05.05] render seam above
    // stays a placeholder.
    private static void AppendScriptSeam(StringBuilder builder, int indent, in SingleFileComponentModel model)
    {
        if (model.Script.MemberRegion is not { } memberRegion)
        {
            AppendIndent(builder, indent);
            if (model.HasScript)
            {
                builder.Append("// [V01.01.06.03.01] The @script block contributes no class-body members; any leading\n");
                AppendIndent(builder, indent);
                builder.Append("// using directives are hoisted into the file's using region above the namespace.\n");
            }
            else
            {
                builder.Append("// [V01.01.06.03] Script merge seam. This component declares no @script block, so no C#\n");
                AppendIndent(builder, indent);
                builder.Append("// body is merged into the partial class.\n");
            }

            return;
        }

        AppendIndent(builder, indent);
        builder.Append("// [V01.01.06.03] Merged @script block. The block's C# is emitted verbatim below, wrapped in\n");
        AppendIndent(builder, indent);
        builder.Append("// #line directives that map every line back to the .viu source, so compiler errors and\n");
        AppendIndent(builder, indent);
        builder.Append("// debugger stepping land in the .viu file rather than this generated file.\n");
        AppendLineMappedRegion(builder, model.FilePath, model.Script.MemberRegionStartLine, memberRegion);
    }

    // Emits a verbatim @script region flush against column 0 (no scaffold indentation added), wrapped in a
    // #line map. The C# #line directive remaps the LINE of the following text but takes each token's COLUMN
    // verbatim from this generated file; because a .viu block's content begins at column 1 (docs/FORMAT.md
    // §3) and both regions split on a line boundary (column 1), emitting each region line un-indented
    // preserves its original column, so a reported (line, column) lands on the exact .viu coordinate — the
    // same block-to-file mapping SingleFileComponentDiagnostics composes. The trailing #line default
    // restores this generated file's own line mapping for whatever follows (the namespace, or the class
    // close). Shared by the hoisted using region (above the namespace) and the merged member region.
    private static void AppendLineMappedRegion(StringBuilder builder, string filePath, int startLine, string content)
    {
        builder.Append("#line ").Append(startLine.ToString(CultureInfo.InvariantCulture))
            .Append(" \"").Append(filePath).Append("\"\n");
        builder.Append(content);
        if (content.Length == 0 || content[content.Length - 1] != '\n')
        {
            builder.Append('\n');
        }

        builder.Append("#line default\n");
    }

    // [V01.01.06.04] The @style seam — emitted at the tail of the class body so it never interleaves with
    // the @script merge region. When the component declares @style blocks, their compiled CSS rides as an
    // ExtractedStyles constant and, for scoped components, the ScopeId constant carries the data-v-<hash>
    // the renderer stamps on elements (the C# analogue of Vue's component __scopeId). No @style block
    // leaves the seam as a documenting comment, matching the render/script seams.
    private static void AppendStyleSeam(StringBuilder builder, int indent, in SingleFileComponentModel model)
    {
        if (model.ExtractedStyles is not { } styles)
        {
            AppendIndent(builder, indent);
            builder.Append("// [V01.01.06.04] Style seam. This component declares no @style block, so no scope id\n");
            AppendIndent(builder, indent);
            builder.Append("// or compiled CSS is emitted.\n");
            return;
        }

        builder.Append('\n');
        AppendIndent(builder, indent);
        builder.Append("// [V01.01.06.04] Compiled @style blocks: scoped blocks are rewritten with the component's\n");
        AppendIndent(builder, indent);
        builder.Append("// data-v-<hash> scope id and non-scoped blocks pass through unmodified. The renderer stamps\n");
        AppendIndent(builder, indent);
        builder.Append("// ScopeId on the component's elements; static-web-asset bundling is the MSBuild follow-up.\n");

        if (model.ScopeId is { } scopeId)
        {
            AppendIndent(builder, indent);
            builder.Append("/// <summary>\n");
            AppendIndent(builder, indent);
            builder.Append("/// The scoped-CSS scope id — the C# analogue of Vue 3.5's component <c>__scopeId</c>. The runtime\n");
            AppendIndent(builder, indent);
            builder.Append("/// renderer stamps this <c>data-v-&lt;hash&gt;</c> attribute on the component's own elements.\n");
            AppendIndent(builder, indent);
            builder.Append("/// </summary>\n");
            AppendIndent(builder, indent);
            builder.Append("internal const string ScopeId = ").Append(Literal(scopeId)).Append(";\n");
            builder.Append('\n');
        }

        AppendIndent(builder, indent);
        builder.Append("/// <summary>\n");
        AppendIndent(builder, indent);
        builder.Append("/// The component's compiled CSS — scoped <c>@style</c> blocks rewritten with <see cref=\"ScopeId\"/>,\n");
        AppendIndent(builder, indent);
        builder.Append("/// non-scoped blocks verbatim — extracted at build time (the WASM runtime does zero CSS work).\n");
        AppendIndent(builder, indent);
        builder.Append("/// </summary>\n");
        AppendIndent(builder, indent);
        builder.Append("internal const string ExtractedStyles = ").Append(Literal(styles)).Append(";\n");

        AppendModuleAccessors(builder, indent, model);
        AppendCssVariableSeam(builder, indent, model);
    }

    // [V01.01.06.06] The @style module accessor seam. Each `module` block's original -> hashed class map is
    // emitted as a nested static class (the C# analogue of Vue's `$style` / useCssModule()) whose const
    // members mirror the declared class names, so a reference to a class that does not exist is a compile
    // error. Blocks that share an accessor (several `@style module` blocks, or `module="name"` repeated)
    // merge into one class; a duplicate member is emitted once.
    private static void AppendModuleAccessors(StringBuilder builder, int indent, in SingleFileComponentModel model)
    {
        if (model.ModuleClasses.Count == 0)
        {
            return;
        }

        var accessors = new List<string>();
        var membersByAccessor = new Dictionary<string, List<(string Member, string Hashed)>>(StringComparer.Ordinal);
        var seen = new HashSet<string>(StringComparer.Ordinal);
        foreach (var entry in model.ModuleClasses)
        {
            var member = MemberName(entry.Original);
            if (!seen.Add(entry.Accessor + "." + member))
            {
                continue;
            }

            if (!membersByAccessor.TryGetValue(entry.Accessor, out var members))
            {
                members = new List<(string, string)>();
                membersByAccessor[entry.Accessor] = members;
                accessors.Add(entry.Accessor);
            }

            members.Add((member, entry.Hashed));
        }

        foreach (var accessor in accessors)
        {
            builder.Append('\n');
            AppendIndent(builder, indent);
            builder.Append("/// <summary>\n");
            AppendIndent(builder, indent);
            builder.Append("/// The typed CSS Modules accessor for this component's <c>@style module</c> block — the C#\n");
            AppendIndent(builder, indent);
            builder.Append("/// analogue of Vue 3.5's <c>$style</c> / <c>useCssModule()</c>. Each member is the locally-hashed\n");
            AppendIndent(builder, indent);
            builder.Append("/// name of the like-named source class, so a reference to an undeclared class fails to compile.\n");
            AppendIndent(builder, indent);
            builder.Append("/// </summary>\n");
            AppendIndent(builder, indent);
            builder.Append("internal static class ").Append(accessor).Append('\n');
            AppendIndent(builder, indent);
            builder.Append("{\n");
            foreach (var (member, hashed) in membersByAccessor[accessor])
            {
                AppendIndent(builder, indent + 1);
                builder.Append("public const string ").Append(member).Append(" = ").Append(Literal(hashed)).Append(";\n");
            }

            AppendIndent(builder, indent);
            builder.Append("}\n");
        }
    }

    // [V01.01.06.06] The v-bind() CSS custom-property seam. Each recorded (hash, expression) binding becomes
    // an entry of the getter the ApplyCssVariables method hands to the UseCssVars runtime — which applies the
    // evaluated values as custom properties on the component root and re-applies them reactively (post-flush)
    // without re-rendering. The expressions arrive already rewritten by the template compiler's binding-metadata
    // pass ([V01.01.06.06.01]) in instance-member mode: an unqualified member resolves against the merged @script
    // members through the implicit `this`, and a Reference<T> member is auto-unwrapped to `.Value`, so
    // `v-bind(count)` (not `v-bind(count.Value)`) updates reactively. This emitter writes them verbatim inside the
    // instance lambda; the render/script seams stay untouched. The component-runtime instantiation calls
    // ApplyCssVariables during setup (that wiring lands with the .viu component runtime); the method is emitted
    // here so the metadata exists for it.
    private static void AppendCssVariableSeam(StringBuilder builder, int indent, in SingleFileComponentModel model)
    {
        if (model.CssVariableBindings.Count == 0)
        {
            return;
        }

        builder.Append('\n');
        AppendIndent(builder, indent);
        builder.Append("/// <summary>\n");
        AppendIndent(builder, indent);
        builder.Append("/// Registers this component's <c>v-bind()</c> CSS custom properties with the <c>UseCssVars</c>\n");
        AppendIndent(builder, indent);
        builder.Append("/// runtime ([V01.01.06.06]) — the C# analogue of the compiled <c>useCssVars(...)</c> call in Vue\n");
        AppendIndent(builder, indent);
        builder.Append("/// 3.5's setup. Call once during the component's setup; the runtime applies the evaluated values as\n");
        AppendIndent(builder, indent);
        builder.Append("/// <c>--&lt;hash&gt;</c> custom properties on the root element(s) and re-applies them on the next flush\n");
        AppendIndent(builder, indent);
        builder.Append("/// when a bound value changes, without re-rendering.\n");
        AppendIndent(builder, indent);
        builder.Append("/// </summary>\n");
        AppendIndent(builder, indent);
        builder.Append("internal void ApplyCssVariables()\n");
        AppendIndent(builder, indent + 1);
        builder.Append("=> global::Assimalign.Viu.RuntimeDom.CssVariables.UseCssVars(() =>\n");
        AppendIndent(builder, indent + 2);
        builder.Append("new global::System.Collections.Generic.Dictionary<string, string>(")
            .Append(Count(model.CssVariableBindings.Count)).Append(")\n");
        AppendIndent(builder, indent + 2);
        builder.Append("{\n");
        foreach (var binding in model.CssVariableBindings)
        {
            AppendIndent(builder, indent + 3);
            builder.Append('[').Append(Literal(binding.Name)).Append("] = global::System.Convert.ToString((object?)(")
                .Append(binding.Expression)
                .Append("), global::System.Globalization.CultureInfo.InvariantCulture) ?? string.Empty,\n");
        }

        AppendIndent(builder, indent + 2);
        builder.Append("});\n");
    }

    // Turns an authored class name into a valid C# member identifier: non-identifier characters become '_'
    // and a leading digit is prefixed with '_'. Deterministic so the accessor is stable across rebuilds.
    // Internal so the template-compile path ([V01.01.05.04.01]) resolves `$style.<member>` references against
    // the exact same member names this emitter writes as the accessor class's consts.
    internal static string MemberName(string original)
    {
        var builder = new StringBuilder(original.Length);
        foreach (var character in original)
        {
            builder.Append(char.IsLetterOrDigit(character) || character == '_' ? character : '_');
        }

        if (builder.Length == 0)
        {
            return "_";
        }

        if (char.IsDigit(builder[0]))
        {
            builder.Insert(0, '_');
        }

        return builder.ToString();
    }

    // A valid C# string literal for arbitrary CSS text (quotes, backslashes, and newlines escaped).
    private static string Literal(string value)
        => Microsoft.CodeAnalysis.CSharp.SymbolDisplay.FormatLiteral(value, quote: true);

    private static string Present(bool present) => present ? "present" : "absent";

    private static string Count(int count) => count.ToString(CultureInfo.InvariantCulture);

    private static void AppendIndent(StringBuilder builder, int levels)
    {
        for (var level = 0; level < levels; level++)
        {
            builder.Append("    ");
        }
    }
}
