using System.Collections.Immutable;
using System.Linq;

using Microsoft.CodeAnalysis;

using Shouldly;
using Xunit;

// The test namespace is nested under Assimalign.Viu.Syntax, so the base cluster's DiagnosticSeverity is
// ambient and shadows Roslyn's; alias the Roslyn enum the reported diagnostics carry.
using RoslynDiagnosticSeverity = Microsoft.CodeAnalysis.DiagnosticSeverity;

namespace Assimalign.Viu.Syntax.Generators.Tests;

/// <summary>
/// Snapshot, diagnostic, and incremental-cache tests for <see cref="SingleFileComponentGenerator"/>.
/// The snapshot locks the emitted partial-class scaffold and its two clearly-marked seams
/// ([V01.01.05.05] render, [V01.01.06.03] script merge); the diagnostic tests pin that both the
/// <c>.viu</c> block container and the dispatched <c>@template</c> parse (the registration seam) surface
/// as Roslyn diagnostics on the <c>.viu</c> file; the cache tests pin that untouched input reuses cached
/// outputs and a structural edit regenerates.
/// </summary>
public sealed class SingleFileComponentGeneratorTests
{
    private const string ProjectDirectory = "C:/proj";
    private const string RootNamespace = "Demo";

    private const string CounterSource =
        "@template {\n" +
        "    <div>{{ message }}</div>\n" +
        "}\n" +
        "\n" +
        "@script {\n" +
        "    public string Message = \"Hello\";\n" +
        "}\n" +
        "\n" +
        "@style scoped {\n" +
        "    .box { color: red; }\n" +
        "}\n";

    [Fact]
    public void Generates_PartialClassWithCompiledRender_ForWellFormedComponent()
    {
        // Snapshot lock: a well-formed .viu produces a deterministic partial class whose header reflects
        // the composed parse (template + script + one style), whose @template block compiles into the
        // [V01.01.05.05] render function (helpers bound BY NAME through the file-level using static of
        // the runtime render-helper surface) wrapped in the [V01.01.05.08] #line span map (the dynamic
        // {{ message }} access anchors a directive that points a C# error at the .viu template line 2,
        // column 13), whose [V01.01.06.07] IComponent bridge (base list + explicit Name + Setup)
        // makes it mountable, whose @script seam ([V01.01.06.03]) stays untouched, whose scoped @style block
        // ([V01.01.06.04]) compiles to the ScopeId + ExtractedStyles constants at the class tail, and
        // whose render body binds by name against both helper surfaces — the runtime-core import and
        // the DOM import ([V01.01.04.09]).
        const string expected =
"""
// <auto-generated/>
#nullable enable

using static global::Assimalign.Viu.RenderHelpers;
using static global::Assimalign.Viu.Browser.DomRenderHelpers;

namespace Demo
{
    // Generated partial-class scaffold for the "Counter" single-file component, compiled from
    // "Counter.viu" by the Assimalign.Viu.Syntax source generator ([V01.01.06.02]).
    //
    // Parsed blocks: @template=present, @script=present, @style=1, custom=0.
    partial class Counter : global::Assimalign.Viu.IComponent
    {
        /// <summary>
        /// The number of render cache slots (<c>v-once</c> subtrees and cached handlers) the
        /// <see cref="Render"/> function uses; the runtime allocates <c>_cache</c> with this length.
        /// </summary>
        internal const int RenderCacheSize = 0;

        /// <summary>
        /// The compiled render function for the <c>@template</c> block ([V01.01.05.05]) — the C#
        /// analogue of the component's compiled <c>render</c> in Vue 3.5 (vuejs/core
        /// packages/compiler-core/src/codegen.ts). The runtime normalizes the returned value.
        /// </summary>
        internal static object? Render(Counter _ctx, object?[] _cache)
        {
#line (2,13)-(2,20) 88 "C:/proj/Counter.viu"
            return _createElementBlock(_openBlock(), "div", null, _toDisplayString(_ctx.message), 1 /* TEXT */);
#line default
        }

        // [V01.01.06.07] The IComponent bridge: the generated Name + Setup that make this
        // compiled @template component mountable through the app builder / VirtualNodeFactory.Component with no
        // hand-written wiring. Explicitly implemented so they never collide with a merged @script member.
        /// <summary>
        /// The component's display name (upstream: the component <c>name</c> option, inferred from the
        /// <c>.viu</c> file name) — surfaced to runtime warnings and devtools.
        /// </summary>
        string? global::Assimalign.Viu.IComponent.Name => "Counter";

        /// <summary>
        /// The Composition API entry point (upstream: <c>setup(props, context)</c>,
        /// https://vuejs.org/api/composition-api-setup.html) generated for this <c>@template</c> component
        /// ([V01.01.06.07]). It runs once per instance: it allocates the per-instance render cache
        /// (<see cref="RenderCacheSize"/> slots) and returns the render delegate, which re-executes the
        /// compiled <see cref="Render"/> on every reactive update. State is the merged <c>@script</c>
        /// members the render reads through <c>_ctx</c>, so a reactive member drives re-render.
        /// </summary>
        /// <param name="properties">The instance's shallow-reactive props (upstream: <c>setup</c>'s <c>props</c>).</param>
        /// <param name="context">The setup context: attrs, emit, expose, and slots.</param>
        /// <returns>The render function producing the component's subtree.</returns>
        global::Assimalign.Viu.ComponentSetup global::Assimalign.Viu.IComponent.Setup(
            global::Assimalign.Viu.ComponentProperties properties,
            global::Assimalign.Viu.ComponentSetupContext context)
        {
            // The per-instance render cache (v-once subtrees and cached handlers), allocated once and
            // captured by the render delegate so cached slots persist across re-renders.
            var _cache = new object?[RenderCacheSize];
            return () => global::Assimalign.Viu.RenderHelpers.NormalizeRoot(Render(this, _cache));
        }

        // [V01.01.06.03] Merged @script block. The block's C# is emitted verbatim below, wrapped in
        // #line directives that map every line back to the .viu source, so compiler errors and
        // debugger stepping land in the .viu file rather than this generated file.
#line 6 "C:/proj/Counter.viu"
    public string Message = "Hello";
#line default

        // [V01.01.06.04] Compiled @style blocks: scoped blocks are rewritten with the component's
        // data-v-<hash> scope id and non-scoped blocks pass through unmodified. The renderer stamps
        // ScopeId on the component's elements; static-web-asset bundling is the MSBuild follow-up.
        /// <summary>
        /// The scoped-CSS scope id — the C# analogue of Vue 3.5's component <c>__scopeId</c>. The runtime
        /// renderer stamps this <c>data-v-&lt;hash&gt;</c> attribute on the component's own elements.
        /// </summary>
        internal const string ScopeId = "data-v-9d968641";

        /// <summary>
        /// The component's compiled CSS — scoped <c>@style</c> blocks rewritten with <see cref="ScopeId"/>,
        /// non-scoped blocks verbatim — extracted at build time (the WASM runtime does zero CSS work).
        /// </summary>
        internal const string ExtractedStyles = ".box[data-v-9d968641] {\n  color: red;\n}\n";
    }
}
""";

        var outcome = GeneratorTestHarness.Run($"{ProjectDirectory}/Counter.viu", CounterSource, RootNamespace, ProjectDirectory);

        outcome.Diagnostics.ShouldBeEmpty();
        Normalize(GeneratorTestHarness.GeneratedSource(outcome, "Counter.SingleFileComponent.g.cs"))
            .ShouldBe(Normalize(expected));
    }

    [Fact]
    public void ComponentWithoutTemplate_EmitsNoRenderFunction()
    {
        // The render seam degrades gracefully: no @template block means no render method, no cache
        // constant, and no using static of the runtime helper surface.
        const string source =
            "@script {\n" +
            "    public int Value;\n" +
            "}\n";

        var outcome = GeneratorTestHarness.Run($"{ProjectDirectory}/Bare.viu", source, RootNamespace, ProjectDirectory);

        var generated = GeneratorTestHarness.GeneratedSource(outcome, "Bare.SingleFileComponent.g.cs");
        generated.ShouldContain("// [V01.01.05.05] No @template block: no render function is emitted for this component.");
        generated.ShouldNotContain("using static");
        generated.ShouldNotContain("internal static object? Render(");
    }

    [Fact]
    public void RenderlessComponent_StaysAPlainPartialClass_WithNoComponentBridge()
    {
        // [V01.01.06.07] The bridge is emitted ONLY for a @template-bearing .viu: a @style-only .viu (the
        // AppStyles.viu / HackerNews CSS-bundle shape) must keep compiling as a plain partial class — no
        // IComponent base list, no Setup — so it never suddenly demands a template or a runtime
        // reference. Pins the "keep @style-only files compiling exactly as today" requirement.
        const string source =
            "@style scoped {\n" +
            "    .box { color: red; }\n" +
            "}\n";

        var outcome = GeneratorTestHarness.Run($"{ProjectDirectory}/AppStyles.viu", source, RootNamespace, ProjectDirectory);

        outcome.Diagnostics.ShouldBeEmpty();
        var generated = GeneratorTestHarness.GeneratedSource(outcome, "AppStyles.SingleFileComponent.g.cs");
        generated.ShouldContain("partial class AppStyles\n");
        generated.ShouldNotContain("IComponent");
        generated.ShouldNotContain(".Setup(");
        generated.ShouldNotContain("using static");
        // The @style seam still compiles to the scope id + extracted CSS exactly as before.
        generated.ShouldContain("internal const string ExtractedStyles = ");
    }

    [Fact]
    public void GeneratedRenderFile_ParsesAsValidCSharp()
    {
        // The compile-check on the full generated file: a component exercising components, slots, v-for,
        // and event handlers must produce syntactically valid C# (semantic binding to the runtime helper
        // surface is the runtime-side integration deliverable pinned in the Templates DESIGN.md).
        const string source =
            "@template {\n" +
            "    <MyButton :kind=\"kind\" @press=\"onPress\">\n" +
            "        <li v-for=\"item in items\" :key=\"item.id\">{{ item.label }}</li>\n" +
            "    </MyButton>\n" +
            "}\n";

        var outcome = GeneratorTestHarness.Run($"{ProjectDirectory}/Rich.viu", source, RootNamespace, ProjectDirectory);

        outcome.Diagnostics.ShouldBeEmpty();
        var generated = GeneratorTestHarness.GeneratedSource(outcome, "Rich.SingleFileComponent.g.cs");
        generated.ShouldContain("var _component_MyButton = _resolveComponent(\"MyButton\");");
        generated.ShouldContain("_withCtx(");
        generated.ShouldContain("_renderList(_ctx.items, (item) => {");
        generated.ShouldContain("_withHandler(_ctx.onPress)");

        var tree = GeneratorTestHarness.Parse(generated);
        tree.GetDiagnostics()
            .Where(diagnostic => diagnostic.Severity == RoslynDiagnosticSeverity.Error)
            .ShouldBeEmpty(customMessage: generated);
    }

    [Fact]
    public void DerivesNamespaceFromSubfolder_AndPathQualifiedHintName()
    {
        // The namespace composes RootNamespace with the file's directory segments and the hint name is
        // path-qualified, so two same-named .viu files in different folders never collide.
        var outcome = GeneratorTestHarness.Run($"{ProjectDirectory}/Components/Counter.viu", CounterSource, RootNamespace, ProjectDirectory);

        var generated = GeneratorTestHarness.GeneratedSource(outcome, "Components.Counter.SingleFileComponent.g.cs");
        generated.ShouldContain("namespace Demo.Components");
        generated.ShouldContain("partial class Counter");
    }

    [Fact]
    public void MalformedComponent_SurfacesContainerDiagnostic_OnViuFile()
    {
        // A stray top-level line is StrayTopLevelContent in the .viu block container; it maps to the
        // VIU1001 error located on the .viu file, and the scaffold is still produced (recoverable).
        const string source =
            "@template {\n" +
            "    <div>ok</div>\n" +
            "}\n" +
            "this is stray top-level content\n";

        var outcome = GeneratorTestHarness.Run($"{ProjectDirectory}/Counter.viu", source, RootNamespace, ProjectDirectory);

        var diagnostic = outcome.Diagnostics.ShouldHaveSingleItem();
        diagnostic.Id.ShouldBe("VIU1001");
        diagnostic.Severity.ShouldBe(RoslynDiagnosticSeverity.Error);
        diagnostic.Location.GetLineSpan().Path.ShouldBe($"{ProjectDirectory}/Counter.viu");
        // Recoverable: the scaffold is emitted even though the file has an error.
        outcome.Sources.ShouldNotBeEmpty();
    }

    [Fact]
    public void MalformedTemplate_SurfacesTemplateDiagnostic_ViaRegistrationSeam()
    {
        // The @template block is dispatched to the registered TemplateSyntaxParser (the composition
        // root's registration seam). An unterminated interpolation is XMissingInterpolationEnd upstream;
        // it maps to the VIU1101 template error on the .viu file, proving the seam actually parses the
        // block content (the .viu container parser never would on its own).
        const string source =
            "@template {\n" +
            "    {{ message\n" +
            "}\n";

        var outcome = GeneratorTestHarness.Run($"{ProjectDirectory}/Counter.viu", source, RootNamespace, ProjectDirectory);

        var diagnostic = outcome.Diagnostics.ShouldHaveSingleItem();
        diagnostic.Id.ShouldBe("VIU1101");
        diagnostic.Location.GetLineSpan().Path.ShouldBe($"{ProjectDirectory}/Counter.viu");
    }

    [Fact]
    public void IdenticalInput_AcrossTwoRuns_ReusesCachedOutputs()
    {
        // Incremental cache contract: running the same driver again over unchanged input leaves the
        // model step Cached - strictly Cached, because Unchanged means the step RE-EXECUTED and merely produced an equal output, the exact regression the caching contract must catch.
        var file = new InMemoryAdditionalText($"{ProjectDirectory}/Counter.viu", CounterSource);
        var compilation = GeneratorTestHarness.CreateCompilation();
        var driver = GeneratorTestHarness.CreateDriver(
            ImmutableArray.Create<AdditionalText>(file), RootNamespace, ProjectDirectory);

        driver = driver.RunGenerators(compilation);
        driver = driver.RunGenerators(compilation);

        ModelStepReasons(driver).ShouldAllBe(
            reason => reason == IncrementalStepRunReason.Cached);
    }

    private const string StaticContentSource =
        "@template {\n" +
        "    <section><span>static</span></section>\n" +
        "}\n";

    [Fact]
    public void StaticSubtree_CompilesToCachedRender_WithCacheSlot()
    {
        // [V01.01.05.07] end to end: a fully static nested subtree caches into a render cache slot, marked
        // PatchFlags.Cached (-1), so the runtime diff skips it. The composition root enables HoistStatic.
        var outcome = GeneratorTestHarness.Run($"{ProjectDirectory}/Static.viu", StaticContentSource, RootNamespace, ProjectDirectory);

        outcome.Diagnostics.ShouldBeEmpty();
        var generated = GeneratorTestHarness.GeneratedSource(outcome, "Static.SingleFileComponent.g.cs");
        generated.ShouldContain("internal const int RenderCacheSize = 1;");
        generated.ShouldContain("(_cache[0] ??= _createElementVNode(\"span\", null, \"static\", -1 /* CACHED */))");
    }

    [Fact]
    public void StaticCaching_DoesNotBreakIncrementalCache()
    {
        // The regression the work item guards: enabling static caching keeps the model step strictly Cached
        // across identical runs (deterministic, value-equatable transform output).
        var file = new InMemoryAdditionalText($"{ProjectDirectory}/Static.viu", StaticContentSource);
        var compilation = GeneratorTestHarness.CreateCompilation();
        var driver = GeneratorTestHarness.CreateDriver(
            ImmutableArray.Create<AdditionalText>(file), RootNamespace, ProjectDirectory);

        driver = driver.RunGenerators(compilation);
        driver = driver.RunGenerators(compilation);

        ModelStepReasons(driver).ShouldAllBe(
            reason => reason == IncrementalStepRunReason.Cached);
    }

    [Fact]
    public void UnrelatedCompilationEdit_DoesNotReRunGeneration()
    {
        // The pipeline depends only on .viu additional files and two build properties, never the
        // compilation, so adding an unrelated C# tree leaves the model step strictly Cached.
        var file = new InMemoryAdditionalText($"{ProjectDirectory}/Counter.viu", CounterSource);
        var compilation = GeneratorTestHarness.CreateCompilation();
        var driver = GeneratorTestHarness.CreateDriver(
            ImmutableArray.Create<AdditionalText>(file), RootNamespace, ProjectDirectory);

        driver = driver.RunGenerators(compilation);
        var withUnrelated = compilation.AddSyntaxTrees(
            GeneratorTestHarness.Parse("namespace Other { internal sealed class Unrelated { public int Value; } }"));
        driver = driver.RunGenerators(withUnrelated);

        ModelStepReasons(driver).ShouldAllBe(
            reason => reason == IncrementalStepRunReason.Cached);
    }

    [Fact]
    public void EditedInput_RegeneratesModel()
    {
        // A structural edit (removing the @script block) changes the model, so the model step re-runs
        // and the regenerated scaffold reflects the change.
        const string edited =
            "@template {\n" +
            "    <div>{{ message }}</div>\n" +
            "}\n" +
            "\n" +
            "@style scoped {\n" +
            "    .box { color: red; }\n" +
            "}\n";

        var file = new InMemoryAdditionalText($"{ProjectDirectory}/Counter.viu", CounterSource);
        var compilation = GeneratorTestHarness.CreateCompilation();
        var driver = GeneratorTestHarness.CreateDriver(
            ImmutableArray.Create<AdditionalText>(file), RootNamespace, ProjectDirectory);

        driver = driver.RunGenerators(compilation);
        driver = driver.ReplaceAdditionalText(file, new InMemoryAdditionalText($"{ProjectDirectory}/Counter.viu", edited));
        driver = driver.RunGenerators(compilation);

        ModelStepReasons(driver).ShouldContain(
            reason => reason == IncrementalStepRunReason.Modified || reason == IncrementalStepRunReason.New);

        var result = driver.GetRunResult().Results[0];
        var generated = result.GeneratedSources
            .Single(source => source.HintName.EndsWith("Counter.SingleFileComponent.g.cs"))
            .SourceText.ToString();
        generated.ShouldContain("@script=absent");
    }

    private static ImmutableArray<IncrementalStepRunReason> ModelStepReasons(GeneratorDriver driver)
        => driver.GetRunResult().Results[0]
            .TrackedSteps[SingleFileComponentGenerator.ModelTrackingName]
            .SelectMany(step => step.Outputs)
            .Select(output => output.Reason)
            .ToImmutableArray();

    private static string Normalize(string text) => text.Replace("\r\n", "\n").TrimEnd() + "\n";

    [Fact]
    public void TemplateDiagnostic_ComposesBlockPositionIntoFileCoordinates()
    {
        // The block-to-file coordinate mapping: the @template content starts on file line 2, and the
        // unterminated interpolation sits on content line 2, so the reported (zero-based) position is
        // file line 2 (= one-based line 3, the "{{ message" line) at column 0 — pinning the
        // Compose() arithmetic, not just the location path.
        const string source =
            "@template {\n" +
            "<b>\n" +
            "{{ message\n" +
            "</b>\n" +
            "}\n";

        var outcome = GeneratorTestHarness.Run($"{ProjectDirectory}/Counter.viu", source, RootNamespace, ProjectDirectory);

        // The unterminated interpolation swallows to EOF, so the unclosed <b> is also reported —
        // both template diagnostics, each composed onto its own .viu file line.
        outcome.Diagnostics.Count().ShouldBe(2);
        var interpolation = outcome.Diagnostics.Single(
            candidate => candidate.GetMessage().Contains("Interpolation end sign"));
        interpolation.Id.ShouldBe("VIU1101");
        // The per-language catalog code rides on the message (CompilerErrorCode.MissingInterpolationEnd = 25).
        interpolation.GetMessage().ShouldContain("(template compiler code 25)");
        var span = interpolation.Location.GetLineSpan();
        span.Path.ShouldBe($"{ProjectDirectory}/Counter.viu");
        span.StartLinePosition.Line.ShouldBe(2);
        span.StartLinePosition.Character.ShouldBe(0);

        var missingEndTag = outcome.Diagnostics.Single(
            candidate => candidate.GetMessage().Contains("missing end tag"));
        missingEndTag.Location.GetLineSpan().StartLinePosition.Line.ShouldBe(1);
    }

    [Fact]
    public void InvalidTemplateExpression_RemapsRoslynSubExpressionSpan_OntoTheViuFile()
    {
        // The [V01.01.05.04] expression-span remapping flows through the generator surface: a syntactically
        // invalid C# expression inside an interpolation is X_INVALID_EXPRESSION (code 45), and the Roslyn
        // sub-expression error span is remapped from expression-relative offsets back through the template
        // offset onto the .viu file — the issue's "expression-level errors remap Roslyn sub-expression spans"
        // acceptance criterion, surfaced as VIU1101.
        const string source =
            "@template {\n" +
            "<div>{{ a + }}</div>\n" +   // `a + ` is missing its right operand
            "}\n";

        var outcome = GeneratorTestHarness.Run($"{ProjectDirectory}/Counter.viu", source, RootNamespace, ProjectDirectory);

        var diagnostic = outcome.Diagnostics.ShouldHaveSingleItem();
        diagnostic.Id.ShouldBe("VIU1101");
        diagnostic.GetMessage().ShouldContain("Error parsing JavaScript expression");
        diagnostic.GetMessage().ShouldContain("(template compiler code 45)"); // X_INVALID_EXPRESSION
        var span = diagnostic.Location.GetLineSpan();
        span.Path.ShouldBe($"{ProjectDirectory}/Counter.viu");
        span.StartLinePosition.Line.ShouldBe(1);        // .viu file line 2, zero-based — inside the interpolation
        span.StartLinePosition.Character.ShouldBe(11);  // the remapped sub-expression span, composed onto the .viu line
    }

    [Fact]
    public void HintNames_OfCollidingSources_AreDisambiguated()
    {
        // Roslyn's AddSource throws on duplicate hint names and the exception kills the whole generator
        // run, so names that sanitize to the same identifier (and files whose location is unknown) get
        // a stable path-hash suffix — unique by construction.
        var dashed = SingleFileComponentNameResolver.Resolve($"{ProjectDirectory}/Foo-Bar.viu", ProjectDirectory, RootNamespace);
        var underscored = SingleFileComponentNameResolver.Resolve($"{ProjectDirectory}/Foo_Bar.viu", ProjectDirectory, RootNamespace);
        dashed.ClassName.ShouldBe("Foo_Bar");
        underscored.ClassName.ShouldBe("Foo_Bar");
        dashed.HintName.ShouldNotBe(underscored.HintName);

        var outside = SingleFileComponentNameResolver.Resolve("/elsewhere/Counter.viu", ProjectDirectory, RootNamespace);
        var inside = SingleFileComponentNameResolver.Resolve($"{ProjectDirectory}/Counter.viu", ProjectDirectory, RootNamespace);
        outside.HintName.ShouldNotBe(inside.HintName);

        // The disambiguator is deterministic — the same path always yields the same hint (the
        // incremental-caching contract).
        SingleFileComponentNameResolver.Resolve("/elsewhere/Counter.viu", ProjectDirectory, RootNamespace)
            .HintName.ShouldBe(outside.HintName);
    }

    [Fact]
    public void GeneratedIdentifiers_EscapeCSharpKeywords()
    {
        // "class.viu" must emit a legal identifier: the class (and any keyword directory segment)
        // gets the verbatim-identifier prefix.
        var resolved = SingleFileComponentNameResolver.Resolve($"{ProjectDirectory}/class.viu", ProjectDirectory, RootNamespace);
        resolved.ClassName.ShouldBe("@class");
        resolved.HintName.ShouldBe("class.SingleFileComponent.g.cs");
    }
}
