using System;
using System.Collections.Generic;

namespace Assimalign.Viu.UtilityCss;

internal static class UtilityRootCatalog
{
    // Candidate parsing needs only root boundaries. Whether a root accepts a particular negative,
    // fraction, modifier, named token, or arbitrary type is intentionally left to the later utility
    // registry. The list pins v4.3.3 functional roots, including roots generated by loops in the
    // compatibility reference rather than appearing as string-literal registrations.
    private static readonly HashSet<string> FunctionalRoots = new(
        new[]
        {
            "@container",
            "accent",
            "align",
            "animate",
            "aspect",
            "auto-cols",
            "auto-rows",
            "backdrop-blur",
            "backdrop-brightness",
            "backdrop-contrast",
            "backdrop-grayscale",
            "backdrop-hue-rotate",
            "backdrop-invert",
            "backdrop-filter",
            "backdrop-opacity",
            "backdrop-saturate",
            "backdrop-sepia",
            "basis",
            "bg",
            "bg-conic",
            "bg-linear",
            "bg-position",
            "bg-radial",
            "bg-size",
            "block",
            "blur",
            "border",
            "border-b",
            "border-be",
            "border-bs",
            "border-e",
            "border-l",
            "border-r",
            "border-s",
            "border-spacing",
            "border-spacing-x",
            "border-spacing-y",
            "border-t",
            "border-x",
            "border-y",
            "bottom",
            "brightness",
            "caret",
            "col",
            "col-end",
            "col-span",
            "col-start",
            "columns",
            "contain",
            "content",
            "contrast",
            "cursor",
            "decoration",
            "delay",
            "divide",
            "divide-x",
            "divide-y",
            "drop-shadow",
            "duration",
            "ease",
            "fill",
            "filter",
            "flex",
            "font",
            "font-features",
            "font-stretch",
            "from",
            "gap",
            "gap-x",
            "gap-y",
            "grayscale",
            "grid-cols",
            "grid-flow",
            "grid-rows",
            "grow",
            "h",
            "hue-rotate",
            "indent",
            "inline",
            "inset",
            "inset-b",
            "inset-be",
            "inset-bs",
            "inset-e",
            "inset-l",
            "inset-r",
            "inset-ring",
            "inset-s",
            "inset-shadow",
            "inset-t",
            "inset-x",
            "inset-y",
            "invert",
            "items",
            "justify",
            "justify-items",
            "justify-self",
            "leading",
            "left",
            "line-clamp",
            "list",
            "list-image",
            "m",
            "mask",
            "mask-b-from",
            "mask-b-to",
            "mask-conic",
            "mask-conic-from",
            "mask-conic-to",
            "mask-l-from",
            "mask-l-to",
            "mask-linear",
            "mask-linear-from",
            "mask-linear-to",
            "mask-position",
            "mask-r-from",
            "mask-r-to",
            "mask-radial",
            "mask-radial-at",
            "mask-radial-from",
            "mask-radial-to",
            "mask-size",
            "mask-t-from",
            "mask-t-to",
            "mask-x-from",
            "mask-x-to",
            "mask-y-from",
            "mask-y-to",
            "max-block",
            "max-h",
            "max-inline",
            "max-w",
            "mb",
            "mbe",
            "mbs",
            "me",
            "min-block",
            "min-h",
            "min-inline",
            "min-w",
            "ml",
            "mr",
            "ms",
            "mt",
            "mx",
            "my",
            "object",
            "opacity",
            "order",
            "origin",
            "outline",
            "outline-offset",
            "p",
            "pb",
            "pbe",
            "pbs",
            "pe",
            "perspective",
            "perspective-origin",
            "pl",
            "placeholder",
            "place-content",
            "place-items",
            "place-self",
            "pr",
            "ps",
            "pt",
            "px",
            "py",
            "right",
            "ring",
            "ring-offset",
            "rotate",
            "rotate-x",
            "rotate-y",
            "rotate-z",
            "row",
            "row-end",
            "row-span",
            "row-start",
            "rounded",
            "rounded-b",
            "rounded-be",
            "rounded-bl",
            "rounded-br",
            "rounded-bs",
            "rounded-e",
            "rounded-ee",
            "rounded-es",
            "rounded-l",
            "rounded-r",
            "rounded-s",
            "rounded-se",
            "rounded-ss",
            "rounded-t",
            "rounded-tl",
            "rounded-tr",
            "saturate",
            "scale",
            "scale-x",
            "scale-y",
            "scale-z",
            "scroll-m",
            "scroll-mb",
            "scroll-mbe",
            "scroll-mbs",
            "scroll-me",
            "scroll-ml",
            "scroll-mr",
            "scroll-ms",
            "scroll-mt",
            "scroll-mx",
            "scroll-my",
            "scroll-p",
            "scroll-pb",
            "scroll-pbe",
            "scroll-pbs",
            "scroll-pe",
            "scroll-pl",
            "scroll-pr",
            "scroll-ps",
            "scroll-pt",
            "scroll-px",
            "scroll-py",
            "scrollbar-thumb",
            "scrollbar-track",
            "sepia",
            "self",
            "shadow",
            "shrink",
            "size",
            "skew",
            "skew-x",
            "skew-y",
            "space-x",
            "space-y",
            "start",
            "stroke",
            "tab",
            "text",
            "text-shadow",
            "to",
            "top",
            "tracking",
            "transform",
            "transition",
            "translate",
            "translate-x",
            "translate-y",
            "translate-z",
            "underline-offset",
            "via",
            "w",
            "will-change",
            "z",
            "zoom",
        },
        StringComparer.Ordinal);

    private static readonly HashSet<string> StaticRoots = new(
        new[]
        {
            "absolute",
            "block",
            "box-border",
            "box-content",
            "contents",
            "fixed",
            "flex",
            "flex-auto",
            "flex-col",
            "flex-col-reverse",
            "flex-initial",
            "flex-none",
            "flex-row",
            "flex-row-reverse",
            "flow-root",
            "grid",
            "hidden",
            "inline",
            "inline-block",
            "inline-flex",
            "inline-grid",
            "relative",
            "static",
            "sticky",
            "table",
            "underline",
        },
        StringComparer.Ordinal);

    public static void SplitNamedUtility(
        string utility,
        out string root,
        out string? value)
    {
        if (StaticRoots.Contains(utility) ||
            UtilityBuiltInCatalog.IsStaticCandidate(utility))
        {
            root = utility;
            value = null;
            return;
        }

        string? bestRoot = null;
        foreach (var possibleRoot in FunctionalRoots)
        {
            if (utility == possibleRoot ||
                (utility.Length > possibleRoot.Length &&
                 utility.StartsWith(possibleRoot, StringComparison.Ordinal) &&
                 utility[possibleRoot.Length] == '-'))
            {
                if (bestRoot is null || possibleRoot.Length > bestRoot.Length)
                {
                    bestRoot = possibleRoot;
                }
            }
        }

        foreach (var possibleRoot in UtilityBuiltInCatalog.KeywordRoots)
        {
            if (utility == possibleRoot ||
                (utility.Length > possibleRoot.Length &&
                 utility.StartsWith(possibleRoot, StringComparison.Ordinal) &&
                 utility[possibleRoot.Length] == '-'))
            {
                if (bestRoot is null || possibleRoot.Length > bestRoot.Length)
                {
                    bestRoot = possibleRoot;
                }
            }
        }

        if (bestRoot is not null)
        {
            root = bestRoot;
            value = utility.Length == bestRoot.Length
                ? null
                : utility.Substring(bestRoot.Length + 1);
            return;
        }

        var separatorIndex = utility.IndexOf('-');
        if (separatorIndex > 0 && separatorIndex < utility.Length - 1)
        {
            root = utility.Substring(0, separatorIndex);
            value = utility.Substring(separatorIndex + 1);
            return;
        }

        root = utility;
        value = null;
    }
}
