using System.Text;

namespace Assimalign.Vue.Reactivity.Generators;

/// <summary>
/// Renders a <see cref="ReactiveClassModel"/> into the partial-class implementation the generator
/// adds — the compiled stand-in for Vue's <c>reactive()</c> proxy. Every emitted member is fully
/// qualified (no <c>using</c>s), nullable-annotated, and free of reflection so the output is
/// trim/AOT-safe. The per-property getter/setter fast path calls
/// <c>Dependency.Track()</c>/<c>Trigger()</c> directly on a sealed field — no interface dispatch —
/// mirroring the hand-written pattern in RuntimeCore's <c>ComponentProperties</c>.
/// </summary>
internal static class ReactiveSourceEmitter
{
    private const string DependencyType = "global::Assimalign.Vue.Reactivity.Dependency";
    private const string ReactiveObjectType = "global::Assimalign.Vue.Reactivity.IReactiveObject";
    private const string TraversableType = "global::Assimalign.Vue.Reactivity.IReactiveTraversable";
    private const string TraversalType = "global::Assimalign.Vue.Reactivity.ReactiveTraversal";
    private const string EqualityComparerType = "global::System.Collections.Generic.EqualityComparer";

    /// <summary>Emits the full generated source for <paramref name="model"/>.</summary>
    /// <param name="model">The class to implement.</param>
    /// <returns>The generated C# source text.</returns>
    public static string Emit(in ReactiveClassModel model)
    {
        var builder = new StringBuilder();
        builder.Append("// <auto-generated/>\n#nullable enable\n\n");

        var indent = 0;
        var hasNamespace = !string.IsNullOrEmpty(model.Namespace);
        if (hasNamespace)
        {
            builder.Append("namespace ").Append(model.Namespace).Append('\n');
            builder.Append("{\n");
            indent = 1;
        }

        foreach (var container in model.ContainingTypes)
        {
            AppendIndent(builder, indent);
            builder.Append("partial ").Append(container.Keyword).Append(' ')
                .Append(container.Name).Append(container.TypeParameterList).Append('\n');
            AppendIndent(builder, indent);
            builder.Append("{\n");
            indent++;
        }

        AppendIndent(builder, indent);
        builder.Append(model.AccessibilityKeyword).Append("partial class ")
            .Append(model.TypeName).Append(model.TypeParameterList)
            .Append(" : ").Append(ReactiveObjectType).Append('\n');
        AppendIndent(builder, indent);
        builder.Append("{\n");

        var bodyIndent = indent + 1;
        EmitProperties(builder, model, bodyIndent);
        EmitRawAccess(builder, bodyIndent);
        EmitDependencyLookup(builder, model, bodyIndent);
        EmitTraversal(builder, model, bodyIndent);

        AppendIndent(builder, indent);
        builder.Append("}\n");

        for (var level = 0; level < model.ContainingTypes.Count; level++)
        {
            indent--;
            AppendIndent(builder, indent);
            builder.Append("}\n");
        }

        if (hasNamespace)
        {
            builder.Append("}\n");
        }

        return builder.ToString();
    }

    private static void EmitProperties(StringBuilder builder, in ReactiveClassModel model, int indent)
    {
        foreach (var property in model.Properties)
        {
            AppendIndent(builder, indent);
            builder.Append("private ").Append(DependencyType).Append(' ')
                .Append(property.DependencyFieldName).Append(" = new ").Append(DependencyType).Append("();\n");

            AppendIndent(builder, indent);
            builder.Append("private ").Append(property.TypeFullName).Append(' ')
                .Append(property.ValueFieldName).Append(" = default!;\n\n");

            AppendIndent(builder, indent);
            builder.Append(property.AccessibilityKeyword).Append("partial ")
                .Append(property.TypeFullName).Append(' ').Append(property.Name).Append('\n');
            AppendIndent(builder, indent);
            builder.Append("{\n");

            AppendIndent(builder, indent + 1);
            builder.Append("get\n");
            AppendIndent(builder, indent + 1);
            builder.Append("{\n");
            AppendIndent(builder, indent + 2);
            builder.Append("this.").Append(property.DependencyFieldName).Append(".Track();\n");
            AppendIndent(builder, indent + 2);
            builder.Append("return this.").Append(property.ValueFieldName).Append(";\n");
            AppendIndent(builder, indent + 1);
            builder.Append("}\n");

            AppendIndent(builder, indent + 1);
            builder.Append(property.SetterModifier).Append("set\n");
            AppendIndent(builder, indent + 1);
            builder.Append("{\n");
            if (model.Readonly)
            {
                AppendIndent(builder, indent + 2);
                builder.Append("global::System.Diagnostics.Debug.WriteLine(\"[Vue warn] Set operation on key \\\"")
                    .Append(property.Name).Append("\\\" failed: target is readonly.\");\n");
            }
            else
            {
                AppendIndent(builder, indent + 2);
                builder.Append("if (!").Append(EqualityComparerType).Append('<').Append(property.TypeFullName)
                    .Append(">.Default.Equals(this.").Append(property.ValueFieldName).Append(", value))\n");
                AppendIndent(builder, indent + 2);
                builder.Append("{\n");
                AppendIndent(builder, indent + 3);
                builder.Append("this.").Append(property.ValueFieldName).Append(" = value;\n");
                AppendIndent(builder, indent + 3);
                builder.Append("this.").Append(property.DependencyFieldName).Append(".Trigger();\n");
                AppendIndent(builder, indent + 2);
                builder.Append("}\n");
            }
            AppendIndent(builder, indent + 1);
            builder.Append("}\n");

            AppendIndent(builder, indent);
            builder.Append("}\n\n");
        }
    }

    private static void EmitRawAccess(StringBuilder builder, int indent)
    {
        AppendIndent(builder, indent);
        builder.Append("object ").Append(ReactiveObjectType).Append(".ToRaw() => this;\n\n");
    }

    private static void EmitDependencyLookup(StringBuilder builder, in ReactiveClassModel model, int indent)
    {
        AppendIndent(builder, indent);
        builder.Append(DependencyType).Append("? ").Append(ReactiveObjectType)
            .Append(".GetDependency(string propertyName)\n");
        AppendIndent(builder, indent);
        builder.Append("{\n");
        AppendIndent(builder, indent + 1);
        builder.Append("switch (propertyName)\n");
        AppendIndent(builder, indent + 1);
        builder.Append("{\n");
        foreach (var property in model.Properties)
        {
            AppendIndent(builder, indent + 2);
            builder.Append("case \"").Append(property.Name).Append("\":\n");
            AppendIndent(builder, indent + 3);
            builder.Append("return this.").Append(property.DependencyFieldName).Append(";\n");
        }
        AppendIndent(builder, indent + 2);
        builder.Append("default:\n");
        AppendIndent(builder, indent + 3);
        builder.Append("return null;\n");
        AppendIndent(builder, indent + 1);
        builder.Append("}\n");
        AppendIndent(builder, indent);
        builder.Append("}\n\n");
    }

    private static void EmitTraversal(StringBuilder builder, in ReactiveClassModel model, int indent)
    {
        AppendIndent(builder, indent);
        builder.Append("void ").Append(TraversableType).Append(".Traverse(").Append(TraversalType)
            .Append(" traversal)\n");
        AppendIndent(builder, indent);
        builder.Append("{\n");
        foreach (var property in model.Properties)
        {
            AppendIndent(builder, indent + 1);
            if (model.Shallow || property.IsValueType)
            {
                // Shallow (root-only) or a value-type leaf: read the property to track it, no descent.
                builder.Append("_ = this.").Append(property.Name).Append(";\n");
            }
            else
            {
                // Deep: read (track) and recurse into nested reactive members.
                builder.Append("traversal.Visit(this.").Append(property.Name).Append(");\n");
            }
        }
        AppendIndent(builder, indent);
        builder.Append("}\n");
    }

    private static void AppendIndent(StringBuilder builder, int levels)
    {
        for (var level = 0; level < levels; level++)
        {
            builder.Append("    ");
        }
    }
}
