using System.Linq;

using Microsoft.CodeAnalysis;

using Shouldly;
using Xunit;

namespace Assimalign.Viu.Generators.Reactivity.Tests;

/// <summary>
/// Snapshot, diagnostic, and incremental-cache tests for <see cref="ReactiveGenerator"/>. The
/// snapshot locks the exact emitted code, which is the contract that matters here: interception is
/// compiled in and the output contains no reflection, so a change that reintroduced either would fail
/// the snapshot before it could reach a trimmed WASM build. The incremental test pins that unrelated
/// edits do not re-run generation.
/// </summary>
public sealed class ReactiveGeneratorTests
{
    private const string TodoItemSource = """
        using Assimalign.Viu.Reactivity;
        namespace Demo;
        [Reactive]
        public partial class TodoItem
        {
            public partial string Title { get; set; }
            public partial bool Done { get; set; }
        }
        """;

    [Fact]
    public void Generates_TrackTriggerImplementation_ForDeepReactiveClass()
    {
        // Snapshot lock: the generated getter tracks, the setter triggers only on an
        // EqualityComparer change, the type implements IReactiveObject (raw access, per-property
        // dependency lookup, deep traversal), and a ReactiveReferences bundle plus ToReferences()
        // exposes per-property write-through references, so destructuring the object keeps reactivity.
        // The emitted shape follows the hand-written ComponentProperties pattern in the core.
        const string expected =
"""
// <auto-generated/>
#nullable enable

namespace Demo
{
    public partial class TodoItem : global::Assimalign.Viu.Reactivity.IReactiveObject
    {
        private global::Assimalign.Viu.Reactivity.Dependency __TitleDependency = new global::Assimalign.Viu.Reactivity.Dependency();
        private string __TitleValue = default!;

        public partial string Title
        {
            get
            {
                this.__TitleDependency.Track(this, "Title");
                return this.__TitleValue;
            }
            set
            {
                if (!global::System.Collections.Generic.EqualityComparer<string>.Default.Equals(this.__TitleValue, value))
                {
                    this.__TitleValue = value;
                    this.__TitleDependency.Trigger(this, "Title");
                }
            }
        }

        private global::Assimalign.Viu.Reactivity.Dependency __DoneDependency = new global::Assimalign.Viu.Reactivity.Dependency();
        private bool __DoneValue = default!;

        public partial bool Done
        {
            get
            {
                this.__DoneDependency.Track(this, "Done");
                return this.__DoneValue;
            }
            set
            {
                if (!global::System.Collections.Generic.EqualityComparer<bool>.Default.Equals(this.__DoneValue, value))
                {
                    this.__DoneValue = value;
                    this.__DoneDependency.Trigger(this, "Done");
                }
            }
        }

        global::Assimalign.Viu.Reactivity.Dependency? global::Assimalign.Viu.Reactivity.IReactiveObject.GetDependency(string propertyName)
        {
            switch (propertyName)
            {
                case "Title":
                    return this.__TitleDependency;
                case "Done":
                    return this.__DoneDependency;
                default:
                    return null;
            }
        }

        global::System.Collections.Generic.IReadOnlyDictionary<string, object?> global::Assimalign.Viu.Reactivity.IReactiveObject.GetMemberValues() =>
            new global::System.Collections.Generic.Dictionary<string, object?>
            {
                ["Title"] = this.Title,
                ["Done"] = this.Done,
            };

        bool global::Assimalign.Viu.Reactivity.IReactiveObject.TrySetMemberValue(string propertyName, object? value)
        {
            switch (propertyName)
            {
                case "Title" when value is null or string:
                    this.Title = (string)value!;
                    return true;
                case "Done" when value is bool:
                    this.Done = (bool)value!;
                    return true;
                default:
                    return false;
            }
        }

        void global::Assimalign.Viu.Reactivity.IReactiveTraversable.Traverse(global::Assimalign.Viu.Reactivity.ReactiveTraversal traversal)
        {
            traversal.Visit(this.Title);
            _ = this.Done;
        }

        public readonly struct ReactiveReferences
        {
            internal ReactiveReferences(TodoItem source)
            {
                this.Title = global::Assimalign.Viu.Reactivity.Reactive.ToRef<string>(() => source.Title, value => source.Title = value);
                this.Done = global::Assimalign.Viu.Reactivity.Reactive.ToRef<bool>(() => source.Done, value => source.Done = value);
            }

            public global::Assimalign.Viu.Reactivity.IReactiveReference<string> Title { get; }

            public global::Assimalign.Viu.Reactivity.IReactiveReference<bool> Done { get; }
        }

        public ReactiveReferences ToReferences() => new ReactiveReferences(this);

        public readonly struct RawValues
        {
            private readonly TodoItem _owner;

            internal RawValues(TodoItem owner)
            {
                this._owner = owner;
            }

            public string Title
            {
                get => this._owner.__TitleValue;
                set => this._owner.__TitleValue = value;
            }

            public bool Done
            {
                get => this._owner.__DoneValue;
                set => this._owner.__DoneValue = value;
            }
        }

        public RawValues ToRawValues() => new RawValues(this);
    }
}
""";

        var outcome = GeneratorTestHarness.Run(TodoItemSource);

        outcome.Diagnostics.ShouldBeEmpty();
        Normalize(GeneratorTestHarness.GeneratedSource(outcome, "TodoItem.Reactive.g.cs"))
            .ShouldBe(Normalize(expected));
    }

    [Fact]
    public void MemberInspection_ScalarDispatch_CompilesAndUsesOrdinarySetters()
    {
        // [DVT-13]: the generated cold seam accepts only its declared scalar types.
        const string source = """
            using Assimalign.Viu.Reactivity;
            [Reactive]
            public partial class ScalarModel
            {
                public partial bool Enabled { get; set; }
                public partial int Count { get; set; }
                public partial long Total { get; set; }
                public partial double Ratio { get; set; }
                public partial decimal Price { get; set; }
                public partial string? Label { get; set; }
                public partial object? Opaque { get; set; }
                public partial int? Optional { get; set; }
            }
            """;
        GeneratorDriver driver = GeneratorTestHarness.CreateDriver().RunGeneratorsAndUpdateCompilation(
            GeneratorTestHarness.CreateCompilation(source), out Compilation compilation, out _);
        compilation.GetDiagnostics().Where(diagnostic => diagnostic.Severity == DiagnosticSeverity.Error)
            .ShouldBeEmpty();
        string generated = driver.GetRunResult().Results[0].GeneratedSources.Single().SourceText.ToString();
        generated.ShouldContain("this.Count = (int)value!;");
        generated.ShouldContain("case \"Label\" when value is null or string:");
        generated.ShouldContain("this.Label = (string?)value!;");
        generated.ShouldNotContain("case \"Opaque\" when");
        generated.ShouldNotContain("case \"Optional\" when");
        generated.ShouldContain("[\"Opaque\"] = this.Opaque,");
    }

    [Fact]
    public void MemberInspection_ReadOnlyModel_EmitsNoWriteDispatch()
    {
        // [DVT-13]: the inspection write surface cannot bypass readonly generated properties.
        const string source = """
            using Assimalign.Viu.Reactivity;
            [Reactive(ReadOnly = true)]
            public partial class ReadOnlyModel
            {
                public partial int Count { get; set; }
            }
            """;
        string generated = GeneratorTestHarness.GeneratedSource(
            GeneratorTestHarness.Run(source), "ReadOnlyModel.Reactive.g.cs");
        generated.ShouldContain(".TrySetMemberValue(string propertyName, object? value)");
        generated.ShouldNotContain("case \"Count\" when");
        generated.ShouldContain("[\"Count\"] = this.Count,");
    }

    [Fact]
    public void ShallowReactive_ReadsRootPropertiesWithoutRecursing_AndNestsPartialContainers()
    {
        const string source = """
            using Assimalign.Viu.Reactivity;
            namespace Demo;
            public partial class Outer
            {
                [ShallowReactive]
                internal partial class Inner
                {
                    public partial int Count { get; set; }
                }
            }
            """;

        var generated = GeneratorTestHarness.GeneratedSource(GeneratorTestHarness.Run(source), "Inner.Reactive.g.cs");

        // Containing type re-declared partial, shallow traversal reads the property (tracks) without
        // descending, so no Visit call is emitted.
        generated.ShouldContain("partial class Outer");
        generated.ShouldContain("internal partial class Inner : global::Assimalign.Viu.Reactivity.IReactiveObject");
        generated.ShouldContain("_ = this.Count;");
        generated.ShouldNotContain("traversal.Visit(");
    }

    [Fact]
    public void ReadOnlyReactive_SetterWarnsAndDoesNotTrigger_ButReadsStillTrack()
    {
        const string source = """
            using Assimalign.Viu.Reactivity;
            namespace Demo;
            [Reactive(ReadOnly = true)]
            public partial class Frozen { public partial string Name { get; set; } }
            """;

        var generated = GeneratorTestHarness.GeneratedSource(GeneratorTestHarness.Run(source), "Frozen.Reactive.g.cs");

        generated.ShouldContain("this.__NameDependency.Track(this, \"Name\");"); // reads still track
        generated.ShouldContain("[Viu warn] Set operation on key \\\"Name\\\" failed: target is read-only.");
        generated.ShouldNotContain(".Trigger("); // readonly setter does not trigger
    }

    [Fact]
    public void ReadOnlyReactive_OverridesIReactiveObjectIsReadOnly_ForIsReadOnly()
    {
        // R6: the readonly flag folded into IReactiveObject. A readonly variant overrides the
        // IReactiveObject.IsReadOnly default-interface member to true so Reactive.IsReadOnly() reports
        // a source-generated readonly object — the port of readonly()'s IS_READONLY flag. There is no
        // separate marker interface any more (the class only implements IReactiveObject).
        const string source = """
            using Assimalign.Viu.Reactivity;
            namespace Demo;
            [Reactive(ReadOnly = true)]
            public partial class Frozen { public partial string Name { get; set; } }
            """;

        var generated = GeneratorTestHarness.GeneratedSource(GeneratorTestHarness.Run(source), "Frozen.Reactive.g.cs");

        generated.ShouldContain("bool global::Assimalign.Viu.Reactivity.IReactiveObject.IsReadOnly => true;");
        generated.ShouldNotContain("IReadonlyReactive");
        generated.ShouldNotContain("IReadOnlyReactive");
    }

    [Theory]
    [InlineData("[Reactive] public class NotPartial { public int Value { get; set; } }", "VUER1001")]
    [InlineData("[Reactive] public static partial class Statics { }", "VUER1002")]
    [InlineData("[Reactive] public partial class InitOnly { public partial string Name { get; init; } }", "VUER1003")]
    public void ReportsDiagnostic_ForMisuse(string declaration, string expectedId)
    {
        var source = "using Assimalign.Viu.Reactivity; namespace Demo { " + declaration + " }";

        var outcome = GeneratorTestHarness.Run(source);

        outcome.Diagnostics.Select(diagnostic => diagnostic.Id).ShouldContain(expectedId);
    }

    [Fact]
    public void ReportsConflictingAttributes_Once_WhenBothReactiveAndShallowReactivePresent()
    {
        const string source = """
            using Assimalign.Viu.Reactivity;
            namespace Demo;
            [Reactive]
            [ShallowReactive]
            public partial class Both { public partial int Value { get; set; } }
            """;

        var outcome = GeneratorTestHarness.Run(source);

        outcome.Diagnostics.Count(diagnostic => diagnostic.Id == "VUER1004").ShouldBe(1);
        // Conflict blocks generation entirely.
        outcome.Sources.ShouldBeEmpty();
    }

    [Fact]
    public void UnrelatedEdit_DoesNotReRunGeneration()
    {
        // Incremental cache contract: adding an unrelated file must leave the reactive model step
        // Cached/Unchanged (Roslyn incremental-generator cookbook).
        var driver = GeneratorTestHarness.CreateDriver();
        var compilation = GeneratorTestHarness.CreateCompilation(TodoItemSource);

        driver = driver.RunGenerators(compilation);
        var withUnrelated = compilation.AddSyntaxTrees(
            GeneratorTestHarness.Parse("namespace Other { internal sealed class Unrelated { public int Value; } }"));
        driver = driver.RunGenerators(withUnrelated);

        var steps = driver.GetRunResult().Results[0].TrackedSteps[ReactiveGenerator.DeepModelTrackingName];
        steps.SelectMany(step => step.Outputs)
            .Select(output => output.Reason)
            .ShouldAllBe(reason => reason == IncrementalStepRunReason.Cached || reason == IncrementalStepRunReason.Unchanged);
    }

    private static string Normalize(string text) => text.Replace("\r\n", "\n").TrimEnd() + "\n";
}
