using System.Globalization;
using System.Text;

namespace Assimalign.Vue.Syntax.Generators;

/// <summary>
/// Renders a <see cref="SingleFileComponentModel"/> into the generated partial class for a <c>.viu</c>
/// component. The output is deterministic and fully statically analyzable (no reflection, no dynamic
/// code generation), so it is trimming- and WASM/NativeAOT-safe. Both seams are filled: the
/// <c>@template</c> block's compiled render function ([V01.01.05.05]) is emitted from the model's
/// pre-serialized render body — helper names bind <b>by name</b> to the runtime render-helper surface
/// through the file-level <c>using static</c> (the generator never references the runtime assembly; the
/// name/signature contract is documented in
/// <c>libraries/Assimalign.Vue.Syntax.Templates/docs/DESIGN.md</c>) — and the <c>@script</c> block's C#
/// ([V01.01.06.03]) is merged verbatim under a <c>#line</c> map so compiler errors and debugger stepping
/// resolve to the <c>.viu</c> source. Beyond the reserved render members (<c>Render</c>,
/// <c>RenderCacheSize</c>), the scaffold emits no members of its own and the class stays
/// <c>partial</c>, so a user-authored sibling <c>.cs</c> partial and the merged script coexist without
/// collision.
/// </summary>
internal static class SingleFileComponentSourceEmitter
{
    /// <summary>
    /// The fully qualified runtime render-helper surface the emitted render body binds against — the C#
    /// analogue of upstream's function-mode <c>const { ... } = _Vue</c> helper import. The type ships
    /// with the runtime block/vnode helpers ([V01.01.05.02] and follow-ups); the generator only ever
    /// names it.
    /// </summary>
    private const string RenderHelperSurface = "global::Assimalign.Vue.RuntimeCore.RenderHelpers";

    /// <summary>Emits the full generated source for <paramref name="model"/>.</summary>
    /// <param name="model">The scaffold to render.</param>
    /// <returns>The generated C# source text.</returns>
    public static string Emit(in SingleFileComponentModel model)
    {
        var builder = new StringBuilder();
        builder.Append("// <auto-generated/>\n#nullable enable\n\n");

        if (model.RenderBody is not null)
        {
            // The by-name binding site for every emitted helper invocation (_openBlock,
            // _createElementBlock, _toDisplayString, ...): one file-level static import, mirroring
            // upstream's aliased helper preamble.
            builder.Append("using static ").Append(RenderHelperSurface).Append(";\n\n");
        }

        var indent = 0;
        var hasNamespace = !string.IsNullOrEmpty(model.Namespace);
        if (hasNamespace)
        {
            builder.Append("namespace ").Append(model.Namespace).Append('\n');
            builder.Append("{\n");
            indent = 1;
        }

        AppendIndent(builder, indent);
        builder.Append("// Generated partial-class scaffold for the \"").Append(model.ClassName)
            .Append("\" single-file component, compiled from\n");
        AppendIndent(builder, indent);
        builder.Append("// \"").Append(model.FileName)
            .Append("\" by the Assimalign.Vue.Syntax source generator ([V01.01.06.02]).\n");
        AppendIndent(builder, indent);
        builder.Append("//\n");
        AppendIndent(builder, indent);
        builder.Append("// Parsed blocks: @template=").Append(Present(model.HasTemplate))
            .Append(", @script=").Append(Present(model.HasScript))
            .Append(", @style=").Append(Count(model.StyleCount))
            .Append(", custom=").Append(Count(model.CustomBlockCount)).Append(".\n");

        AppendIndent(builder, indent);
        builder.Append("partial class ").Append(model.ClassName).Append('\n');
        AppendIndent(builder, indent);
        builder.Append("{\n");

        var bodyIndent = indent + 1;
        if (model.RenderBody is { } renderBody)
        {
            // [V01.01.05.05] The compiled @template render function. The body was serialized by the
            // template compiler's RenderFunctionEmitter (the Vue 3.5 codegen.ts analogue) and is
            // already indented for this nesting depth.
            AppendIndent(builder, bodyIndent);
            builder.Append("/// <summary>\n");
            AppendIndent(builder, bodyIndent);
            builder.Append("/// The number of render cache slots (<c>v-once</c> subtrees and cached handlers) the\n");
            AppendIndent(builder, bodyIndent);
            builder.Append("/// <see cref=\"Render\"/> function uses; the runtime allocates <c>_cache</c> with this length.\n");
            AppendIndent(builder, bodyIndent);
            builder.Append("/// </summary>\n");
            AppendIndent(builder, bodyIndent);
            builder.Append("internal const int RenderCacheSize = ").Append(Count(model.RenderCacheSize)).Append(";\n");
            builder.Append('\n');
            AppendIndent(builder, bodyIndent);
            builder.Append("/// <summary>\n");
            AppendIndent(builder, bodyIndent);
            builder.Append("/// The compiled render function for the <c>@template</c> block ([V01.01.05.05]) — the C#\n");
            AppendIndent(builder, bodyIndent);
            builder.Append("/// analogue of the component's compiled <c>render</c> in Vue 3.5 (vuejs/core\n");
            AppendIndent(builder, bodyIndent);
            builder.Append("/// packages/compiler-core/src/codegen.ts). The runtime normalizes the returned value.\n");
            AppendIndent(builder, bodyIndent);
            builder.Append("/// </summary>\n");
            AppendIndent(builder, bodyIndent);
            builder.Append("internal static object? Render(").Append(model.ClassName).Append(" _ctx, object?[] _cache)\n");
            AppendIndent(builder, bodyIndent);
            builder.Append("{\n");
            builder.Append(renderBody);
            AppendIndent(builder, bodyIndent);
            builder.Append("}\n");
        }
        else
        {
            AppendIndent(builder, bodyIndent);
            builder.Append("// [V01.01.05.05] No @template block: no render function is emitted for this component.\n");
        }

        builder.Append('\n');

        AppendScriptSeam(builder, bodyIndent, model);

        AppendStyleSeam(builder, bodyIndent, model);

        AppendIndent(builder, indent);
        builder.Append("}\n");

        if (hasNamespace)
        {
            builder.Append("}\n");
        }

        return builder.ToString();
    }

    // [V01.01.06.03] The @script merge seam — the only seam this work item fills. When the component
    // declares a script block, its C# body is merged into the partial class under a #line map; otherwise
    // the seam is a documenting comment. The [V01.01.05.05] render seam above stays a placeholder.
    private static void AppendScriptSeam(StringBuilder builder, int indent, in SingleFileComponentModel model)
    {
        if (model.ScriptContent is not { } scriptContent)
        {
            AppendIndent(builder, indent);
            builder.Append("// [V01.01.06.03] Script merge seam. This component declares no @script block, so no C#\n");
            AppendIndent(builder, indent);
            builder.Append("// body is merged into the partial class.\n");
            return;
        }

        AppendIndent(builder, indent);
        builder.Append("// [V01.01.06.03] Merged @script block. The block's C# is emitted verbatim below, wrapped in\n");
        AppendIndent(builder, indent);
        builder.Append("// #line directives that map every line back to the .viu source, so compiler errors and\n");
        AppendIndent(builder, indent);
        builder.Append("// debugger stepping land in the .viu file rather than this generated file.\n");
        AppendScript(builder, model.FilePath, model.ScriptContentStartLine, scriptContent);
    }

    // Emits the @script body flush against column 0 (no scaffold indentation added). The C# #line
    // directive remaps the LINE of the following text but takes each token's COLUMN verbatim from this
    // generated file; because a .viu block's content begins at column 1 (docs/FORMAT.md §3), emitting each
    // script line un-indented preserves its original column, so a reported (line, column) lands on the
    // exact .viu coordinate — the same block-to-file mapping SingleFileComponentDiagnostics composes. The
    // trailing #line default restores this generated file's own line mapping for the scaffold that follows.
    private static void AppendScript(StringBuilder builder, string filePath, int startLine, string content)
    {
        builder.Append("#line ").Append(startLine.ToString(CultureInfo.InvariantCulture))
            .Append(" \"").Append(filePath).Append("\"\n");
        builder.Append(content);
        if (content.Length == 0 || content[content.Length - 1] != '\n')
        {
            builder.Append('\n');
        }

        builder.Append("#line default\n");
    }

    // [V01.01.06.04] The @style seam — emitted at the tail of the class body so it never interleaves with
    // the @script merge region. When the component declares @style blocks, their compiled CSS rides as an
    // ExtractedStyles constant and, for scoped components, the ScopeId constant carries the data-v-<hash>
    // the renderer stamps on elements (the C# analogue of Vue's component __scopeId). No @style block
    // leaves the seam as a documenting comment, matching the render/script seams.
    private static void AppendStyleSeam(StringBuilder builder, int indent, in SingleFileComponentModel model)
    {
        if (model.ExtractedStyles is not { } styles)
        {
            AppendIndent(builder, indent);
            builder.Append("// [V01.01.06.04] Style seam. This component declares no @style block, so no scope id\n");
            AppendIndent(builder, indent);
            builder.Append("// or compiled CSS is emitted.\n");
            return;
        }

        builder.Append('\n');
        AppendIndent(builder, indent);
        builder.Append("// [V01.01.06.04] Compiled @style blocks: scoped blocks are rewritten with the component's\n");
        AppendIndent(builder, indent);
        builder.Append("// data-v-<hash> scope id and non-scoped blocks pass through unmodified. The renderer stamps\n");
        AppendIndent(builder, indent);
        builder.Append("// ScopeId on the component's elements; static-web-asset bundling is the MSBuild follow-up.\n");

        if (model.ScopeId is { } scopeId)
        {
            AppendIndent(builder, indent);
            builder.Append("/// <summary>\n");
            AppendIndent(builder, indent);
            builder.Append("/// The scoped-CSS scope id — the C# analogue of Vue 3.5's component <c>__scopeId</c>. The runtime\n");
            AppendIndent(builder, indent);
            builder.Append("/// renderer stamps this <c>data-v-&lt;hash&gt;</c> attribute on the component's own elements.\n");
            AppendIndent(builder, indent);
            builder.Append("/// </summary>\n");
            AppendIndent(builder, indent);
            builder.Append("internal const string ScopeId = ").Append(Literal(scopeId)).Append(";\n");
            builder.Append('\n');
        }

        AppendIndent(builder, indent);
        builder.Append("/// <summary>\n");
        AppendIndent(builder, indent);
        builder.Append("/// The component's compiled CSS — scoped <c>@style</c> blocks rewritten with <see cref=\"ScopeId\"/>,\n");
        AppendIndent(builder, indent);
        builder.Append("/// non-scoped blocks verbatim — extracted at build time (the WASM runtime does zero CSS work).\n");
        AppendIndent(builder, indent);
        builder.Append("/// </summary>\n");
        AppendIndent(builder, indent);
        builder.Append("internal const string ExtractedStyles = ").Append(Literal(styles)).Append(";\n");
    }

    // A valid C# string literal for arbitrary CSS text (quotes, backslashes, and newlines escaped).
    private static string Literal(string value)
        => Microsoft.CodeAnalysis.CSharp.SymbolDisplay.FormatLiteral(value, quote: true);

    private static string Present(bool present) => present ? "present" : "absent";

    private static string Count(int count) => count.ToString(CultureInfo.InvariantCulture);

    private static void AppendIndent(StringBuilder builder, int levels)
    {
        for (var level = 0; level < levels; level++)
        {
            builder.Append("    ");
        }
    }
}
