using System.Globalization;
using System.Text;

namespace Assimalign.Vue.Syntax.Generators;

/// <summary>
/// Renders a <see cref="SingleFileComponentModel"/> into the partial-class scaffold the generator adds
/// for a <c>.viu</c> component. The output is deterministic and fully statically analyzable (no
/// reflection, no runtime type references), so it is trimming- and WASM/NativeAOT-safe. The scaffold is
/// intentionally a shell with two clearly-marked seams: the render function ([V01.01.05.05]) and the
/// merged <c>@script</c> C# ([V01.01.06.03]) fill in their bodies in their own work items — this
/// composition root emits the seam, not their internals.
/// </summary>
internal static class SingleFileComponentSourceEmitter
{
    /// <summary>Emits the full generated source for <paramref name="model"/>.</summary>
    /// <param name="model">The scaffold to render.</param>
    /// <returns>The generated C# source text.</returns>
    public static string Emit(in SingleFileComponentModel model)
    {
        var builder = new StringBuilder();
        builder.Append("// <auto-generated/>\n#nullable enable\n\n");

        var indent = 0;
        var hasNamespace = !string.IsNullOrEmpty(model.Namespace);
        if (hasNamespace)
        {
            builder.Append("namespace ").Append(model.Namespace).Append('\n');
            builder.Append("{\n");
            indent = 1;
        }

        AppendIndent(builder, indent);
        builder.Append("// Generated partial-class scaffold for the \"").Append(model.ClassName)
            .Append("\" single-file component, compiled from\n");
        AppendIndent(builder, indent);
        builder.Append("// \"").Append(model.FileName)
            .Append("\" by the Assimalign.Vue.Syntax source generator ([V01.01.06.02]).\n");
        AppendIndent(builder, indent);
        builder.Append("//\n");
        AppendIndent(builder, indent);
        builder.Append("// Parsed blocks: @template=").Append(Present(model.HasTemplate))
            .Append(", @script=").Append(Present(model.HasScript))
            .Append(", @style=").Append(Count(model.StyleCount))
            .Append(", custom=").Append(Count(model.CustomBlockCount)).Append(".\n");

        AppendIndent(builder, indent);
        builder.Append("partial class ").Append(model.ClassName).Append('\n');
        AppendIndent(builder, indent);
        builder.Append("{\n");

        var bodyIndent = indent + 1;
        AppendIndent(builder, bodyIndent);
        builder.Append("// [V01.01.05.05] Render function placeholder. The compiled @template render body is emitted\n");
        AppendIndent(builder, bodyIndent);
        builder.Append("// here once template code generation lands; the scaffold emits no render output yet.\n");
        builder.Append('\n');
        AppendIndent(builder, bodyIndent);
        builder.Append("// [V01.01.06.03] Script merge seam. The @script block's C# is merged into this partial class\n");
        AppendIndent(builder, bodyIndent);
        builder.Append("// (with #line mapping) once script analysis lands; the scaffold emits no @script body yet.\n");

        AppendIndent(builder, indent);
        builder.Append("}\n");

        if (hasNamespace)
        {
            builder.Append("}\n");
        }

        return builder.ToString();
    }

    private static string Present(bool present) => present ? "present" : "absent";

    private static string Count(int count) => count.ToString(CultureInfo.InvariantCulture);

    private static void AppendIndent(StringBuilder builder, int levels)
    {
        for (var level = 0; level < levels; level++)
        {
            builder.Append("    ");
        }
    }
}
