#!/usr/bin/env pwsh
<#
.SYNOPSIS
    Generates src/Internal/HtmlNamedCharacterReferences.g.cs from the WHATWG named character
    reference table.

.DESCRIPTION
    The template tokenizer decodes HTML named character references (e.g. &amp; &copy; &notin;) from an
    embedded, compile-time table — never from a runtime DOM or the network ([V01.01.05.01] AOT boundary).
    This script transforms the authoritative WHATWG entities list into a C# lookup keyed by the reference
    name WITHOUT the leading '&' (the trailing ';' is retained where the reference requires it, so the
    keys encode the legacy no-semicolon rules directly).

    The generated file is committed; regenerate only when the WHATWG list changes.

.PARAMETER EntitiesJsonPath
    Path to entities.json. Download the authoritative copy from https://html.spec.whatwg.org/entities.json
    (also mirrored in vuejs/core's `entities` dependency).

.PARAMETER OutputPath
    Path to the generated .cs file. Defaults to the sibling src/Internal/HtmlNamedCharacterReferences.g.cs.

.EXAMPLE
    ./Generate-HtmlEntities.ps1 -EntitiesJsonPath ./entities.json
#>
[CmdletBinding()]
param(
    [Parameter(Mandatory = $true)]
    [string]$EntitiesJsonPath,

    [string]$OutputPath = (Join-Path $PSScriptRoot '../src/Internal/HtmlNamedCharacterReferences.g.cs')
)

$ErrorActionPreference = 'Stop'

# System.Text.Json (not ConvertFrom-Json): the WHATWG list contains keys that differ only in case
# (e.g. "&DownArrow;" vs "&Downarrow;"), which the PowerShell JSON object model cannot represent.
$jsonText = [System.IO.File]::ReadAllText([System.IO.Path]::GetFullPath($EntitiesJsonPath))
$document = [System.Text.Json.JsonDocument]::Parse($jsonText)

# Escape a decoded string into a C# string-literal body: printable ASCII stays literal (with " and \
# escaped), everything else becomes \uXXXX so the generated source contains no literal control or
# non-ASCII characters (repo rule: never write literal control characters into source files).
function ConvertTo-CSharpLiteral([string]$value) {
    $sb = [System.Text.StringBuilder]::new()
    foreach ($ch in $value.ToCharArray()) {
        $code = [int]$ch
        if ($ch -eq '"') {
            [void]$sb.Append('\"')
        }
        elseif ($ch -eq '\') {
            [void]$sb.Append('\\')
        }
        elseif ($code -ge 0x20 -and $code -le 0x7E) {
            [void]$sb.Append($ch)
        }
        else {
            [void]$sb.Append('\u')
            [void]$sb.Append($code.ToString('x4'))
        }
    }
    return $sb.ToString()
}

$entries = [System.Collections.Generic.List[object]]::new()
foreach ($property in $document.RootElement.EnumerateObject()) {
    $name = $property.Name            # e.g. "&amp;" or "&amp"
    $key = $name.Substring(1)         # strip leading '&' -> "amp;" / "amp"
    $characters = $property.Value.GetProperty('characters').GetString()
    $entries.Add([pscustomobject]@{ Key = $key; Value = $characters })
}

# Deterministic ordinal ordering so the generated file is stable across runs.
$sorted = $entries | Sort-Object -Property Key -CaseSensitive

$builder = [System.Text.StringBuilder]::new()
[void]$builder.AppendLine('// <auto-generated>')
[void]$builder.AppendLine('//     Generated by tools/Generate-HtmlEntities.ps1 from the WHATWG named character reference')
[void]$builder.AppendLine('//     list (https://html.spec.whatwg.org/entities.json). DO NOT EDIT BY HAND.')
[void]$builder.AppendLine("//     Entry count: $($sorted.Count) named references (with and without the trailing ';').")
[void]$builder.AppendLine('// </auto-generated>')
[void]$builder.AppendLine()
[void]$builder.AppendLine('using System.Collections.Generic;')
[void]$builder.AppendLine()
[void]$builder.AppendLine('namespace Assimalign.Vue.Compiler;')
[void]$builder.AppendLine()
[void]$builder.AppendLine('/// <summary>')
[void]$builder.AppendLine('/// The embedded WHATWG named character reference table, keyed by reference name without the leading')
[void]$builder.AppendLine("/// <c>&amp;</c> (the trailing <c>;</c> is retained where required). Generated compile-time data — no")
[void]$builder.AppendLine('/// runtime DOM or network access. See <c>tools/Generate-HtmlEntities.ps1</c>.')
[void]$builder.AppendLine('/// </summary>')
[void]$builder.AppendLine('internal static class HtmlNamedCharacterReferences')
[void]$builder.AppendLine('{')
[void]$builder.AppendLine('    /// <summary>The number of named references in <see cref="Table"/>.</summary>')
[void]$builder.AppendLine("    public const int Count = $($sorted.Count);")
[void]$builder.AppendLine()
[void]$builder.AppendLine('    /// <summary>Maps a named reference (no leading <c>&amp;</c>) to its decoded characters.</summary>')
[void]$builder.AppendLine("    public static readonly Dictionary<string, string> Table = new($($sorted.Count), System.StringComparer.Ordinal)")
[void]$builder.AppendLine('    {')
foreach ($entry in $sorted) {
    $k = ConvertTo-CSharpLiteral $entry.Key
    $v = ConvertTo-CSharpLiteral $entry.Value
    [void]$builder.AppendLine("        [`"$k`"] = `"$v`",")
}
[void]$builder.AppendLine('    };')
[void]$builder.AppendLine('}')

$resolvedOutput = [System.IO.Path]::GetFullPath($OutputPath)
[System.IO.File]::WriteAllText($resolvedOutput, $builder.ToString(), [System.Text.UTF8Encoding]::new($false))
Write-Host "Wrote $($sorted.Count) named references to $resolvedOutput"
