using System;
using System.Collections.Generic;
using System.Text;
using System.Threading;

using Assimalign.Viu.Syntax.SingleFileComponent;

namespace Assimalign.Viu.Tooling.Css;

/// <summary>
/// Composes a project's per-component compiled <c>@style</c> CSS into one deterministic bundle string — the
/// pure (I/O-free) core of the <c>ViuBundleCss</c> MSBuild task ([V01.01.12.12]). It resolves each
/// component's scope id, parses and compiles its styles through the shared
/// <see cref="SingleFileComponentStyleCompiler"/> (the identical path the generator runs, so each segment is
/// byte-identical to that component's generated <c>ExtractedStyles</c> constant), drops components with no
/// styles, orders the survivors by project-relative path, and concatenates them under a documented,
/// LF-only layout. The task wraps this with file reads, an incremental write, and static-web-asset
/// registration.
/// <para>
/// <b>Bundle layout</b> (stable, so the incremental cache and byte-comparison hold):
/// <list type="number">
/// <item>a single header comment line, then a blank line;</item>
/// <item>for each component, in ascending ordinal order of its project-relative path (normalized to forward
/// slashes): a <c>/* &lt;relative-path&gt; (&lt;scope-id&gt;) */</c> comment line, the component's compiled
/// CSS verbatim (which already ends in a newline), then a blank separator line.</item>
/// </list>
/// Every newline the bundler itself emits is <c>\n</c>; the compiled CSS segments are LF for scoped / module
/// / <c>v-bind()</c> blocks (the canonical serializer emits <c>\n</c>) and preserve source newlines only for
/// verbatim pass-through blocks — matching the generator's constant exactly.
/// </para>
/// This bundles opaque compiled-CSS strings; it embeds no utility-specific knowledge, so the future
/// utility-first stylesheet ([V01.01.12.16]) plugs a second opaque CSS source into the same task without
/// changing this contract (see <c>docs/UTILITY-CSS-DESIGN.md</c> §2.4).
/// </summary>
public static class SingleFileComponentStyleBundler
{
    private const string Header =
        "/* <auto-generated> Viu single-file-component styles ([V01.01.12.12]). "
        + "Do not edit — regenerated by the ViuBundleCss MSBuild task. */";

    /// <summary>
    /// Compiles and bundles the <c>@style</c> CSS of <paramref name="components"/>.
    /// </summary>
    /// <param name="components">The project's <c>.viu</c> components (path + already-read text).</param>
    /// <param name="projectDirectory">The consuming project's directory, or <see langword="null"/> when unknown (drives the project-relative scope-id hash and ordering).</param>
    /// <param name="cancellationToken">Cancels the compilation.</param>
    /// <returns>
    /// The deterministic bundle text, or <see langword="null"/> when no component declares any
    /// <c>@style</c> block (so the task writes no asset).
    /// </returns>
    /// <exception cref="ArgumentNullException"><paramref name="components"/> is <see langword="null"/>.</exception>
    public static string? Bundle(
        IEnumerable<SingleFileComponentStyleInput> components,
        string? projectDirectory,
        CancellationToken cancellationToken = default)
    {
        if (components is null)
        {
            throw new ArgumentNullException(nameof(components));
        }

        // Style-only composition: the bundler never needs @template compilation, and an @style block parses
        // identically with or without the template registration (see CreateForStyleExtraction), so the
        // compiled CSS stays byte-identical to the generator's while the task avoids loading the template
        // compiler and Roslyn.
        var parser = SingleFileComponentParserFactory.CreateForStyleExtraction();
        var entries = new List<BundleEntry>();

        foreach (var component in components)
        {
            cancellationToken.ThrowIfCancellationRequested();

            var scopeId = StyleScopeId.Resolve(component.FilePath, projectDirectory);
            var parse = parser.ParseComponent(component.Text, cancellationToken);
            var compilation = SingleFileComponentStyleCompiler.Compile(parse, scopeId, cancellationToken);
            if (string.IsNullOrEmpty(compilation.ExtractedStyles))
            {
                continue;
            }

            entries.Add(new BundleEntry(
                RelativePath(component.FilePath, projectDirectory),
                scopeId,
                compilation.ExtractedStyles!));
        }

        if (entries.Count == 0)
        {
            return null;
        }

        // Deterministic order: ascending ordinal of the project-relative path. Ordinal (not culture-aware)
        // so the bundle is byte-stable across machines and locales — the incremental-cache contract.
        entries.Sort(static (left, right) => string.CompareOrdinal(left.RelativePath, right.RelativePath));

        var builder = new StringBuilder();
        builder.Append(Header).Append('\n').Append('\n');
        foreach (var entry in entries)
        {
            builder.Append("/* ").Append(entry.RelativePath).Append(" (").Append(entry.ScopeId).Append(") */").Append('\n');
            builder.Append(entry.Css);
            // The compiled CSS already ends in '\n' (the compiler guarantees a trailing newline); add one
            // more so a blank line separates components. A defensive guard keeps output stable even if a
            // verbatim pass-through block ever lacked its trailing newline.
            if (entry.Css.Length == 0 || entry.Css[entry.Css.Length - 1] != '\n')
            {
                builder.Append('\n');
            }

            builder.Append('\n');
        }

        return builder.ToString();
    }

    // The component's path relative to the project directory (forward slashes), for the bundle comment and
    // ordering. Mirrors StyleScopeId's relative-path derivation so the comment names the same short path the
    // scope-id hash is computed over; falls back to the leaf name for a linked file outside the project.
    private static string RelativePath(string filePath, string? projectDirectory)
    {
        var normalizedPath = filePath.Replace('\\', '/');

        if (!string.IsNullOrEmpty(projectDirectory))
        {
            var normalizedDirectory = projectDirectory!.Replace('\\', '/').TrimEnd('/');
            var prefix = normalizedDirectory + "/";
            if (normalizedPath.StartsWith(prefix, StringComparison.OrdinalIgnoreCase))
            {
                return normalizedPath.Substring(prefix.Length);
            }
        }

        var lastSlash = normalizedPath.LastIndexOf('/');
        return lastSlash >= 0 ? normalizedPath.Substring(lastSlash + 1) : normalizedPath;
    }

    private readonly struct BundleEntry
    {
        public BundleEntry(string relativePath, string scopeId, string css)
        {
            RelativePath = relativePath;
            ScopeId = scopeId;
            Css = css;
        }

        public string RelativePath { get; }

        public string ScopeId { get; }

        public string Css { get; }
    }
}
