using System;
using System.Collections.Immutable;
using System.Text;

using Assimalign.Viu.Compiler.SingleFileComponent;

namespace Assimalign.Viu.Generators.Syntax;

/// <summary>
/// Emits the one-per-consumer-assembly registration catalog and tier-three render glue. The glue
/// calls only the adopted public runtime surface and BCL contracts; no state or type identity is
/// copied across assemblies. Specified by <c>[SFC-CG-2]</c> through <c>[SFC-CG-4]</c>.
/// </summary>
/// <remarks>
/// The catalog is this emitter's own; the glue text is
/// <see cref="SingleFileComponentRenderGlue.Source"/>, shared with the language service so the
/// editor's compilation contains the same glue this build writes.
/// </remarks>
internal static class SingleFileComponentAssemblyEmitter
{
    /// <summary>The deterministic hint name for the assembly-wide generated source.</summary>
    public const string HintName = "Viu.SingleFileComponentAssembly.g.cs";

    /// <summary>Emits the assembly catalog and internal glue.</summary>
    /// <param name="rootNamespace">The consumer's root namespace, or <see langword="null"/>.</param>
    /// <param name="registrations">The generated component registrations in the compilation.</param>
    /// <returns>The complete assembly-wide generated source.</returns>
    public static string Emit(
        string? rootNamespace,
        ImmutableArray<GeneratedComponentRegistration> registrations)
    {
        var ordered = new GeneratedComponentRegistration[registrations.Length];
        registrations.CopyTo(ordered);
        Array.Sort(ordered, static (left, right) =>
            StringComparer.Ordinal.Compare(left.FilePath, right.FilePath));

        var builder = new StringBuilder();
        builder.Append("// <auto-generated/>\n#nullable enable\n\n");
        var hasNamespace = !string.IsNullOrEmpty(rootNamespace);
        if (hasNamespace)
        {
            builder.Append("namespace ").Append(rootNamespace).Append("\n{\n");
        }

        var indent = hasNamespace ? "    " : string.Empty;
        builder.Append(indent)
            .Append("/// <summary>Registers every compiled single-file component in this assembly.</summary>\n")
            .Append(indent)
            .Append("[global::System.CodeDom.Compiler.GeneratedCode(\"Assimalign.Viu.Generators.Syntax\", \"1.0.0.0\")]\n")
            .Append(indent)
            .Append("public static class GeneratedViuComponents\n")
            .Append(indent)
            .Append("{\n")
            .Append(indent)
            .Append("    /// <summary>Adds every generated registration to the supplied factory.</summary>\n")
            .Append(indent)
            .Append("    /// <param name=\"factory\">The application-owned component factory.</param>\n")
            .Append(indent)
            .Append("    public static void Register(global::Assimalign.Viu.Components.ComponentFactory factory)\n")
            .Append(indent)
            .Append("    {\n")
            .Append(indent)
            .Append("        global::System.ArgumentNullException.ThrowIfNull(factory);\n");

        foreach (var registration in ordered)
        {
            builder.Append(indent).Append("        factory.Register(")
                .Append(QualifiedTypeName(registration))
                .Append(".__ViuRegistration);\n");
        }

        builder.Append(indent).Append("    }\n")
            .Append(indent).Append("}\n");

        bool hasServerRenders = false;
        foreach (var registration in ordered)
        {
            if (registration.HasServerRender)
            {
                hasServerRenders = true;
                break;
            }
        }

        if (hasServerRenders)
        {
            builder.Append('\n')
                .Append(indent)
                .Append("/// <summary>Registers every compiler-produced server render in this assembly.</summary>\n")
                .Append(indent)
                .Append("[global::System.CodeDom.Compiler.GeneratedCode(\"Assimalign.Viu.Generators.Syntax\", \"1.0.0.0\")]\n")
                .Append(indent)
                .Append("public static class GeneratedViuServerRenders\n")
                .Append(indent)
                .Append("{\n")
                .Append(indent)
                .Append("    /// <summary>Adds every generated server registration to the supplied registry.</summary>\n")
                .Append(indent)
                .Append("    /// <param name=\"registry\">The server-host-owned render registry.</param>\n")
                .Append(indent)
                .Append("    public static void Register(global::Assimalign.Viu.ServerRenderer.ServerRenderRegistry registry)\n")
                .Append(indent)
                .Append("    {\n")
                .Append(indent)
                .Append("        global::System.ArgumentNullException.ThrowIfNull(registry);\n");

            foreach (var registration in ordered)
            {
                if (registration.HasServerRender)
                {
                    builder.Append(indent).Append("        registry.Register(")
                        .Append(QualifiedTypeName(registration))
                        .Append(".__ViuServerRenderRegistration);\n");
                }
            }

            builder.Append(indent).Append("    }\n")
                .Append(indent).Append("}\n");
        }

        if (hasNamespace)
        {
            builder.Append("}\n");
        }

        builder.Append(SingleFileComponentRenderGlue.Source);
        return builder.ToString();
    }

    private static string QualifiedTypeName(in GeneratedComponentRegistration registration)
        => registration.Namespace is null
            ? "global::" + registration.ClassName
            : "global::" + registration.Namespace + "." + registration.ClassName;
}
