namespace Assimalign.Viu.Generators.Syntax;

/// <summary>
/// Emits the one [V01.01.06.05] metadata-update handler registered on a consuming Debug/opt-in
/// assembly. Keeping the assembly attribute and forwarding methods in one source isolates the
/// runtime-facing API from each generated component.
/// </summary>
internal static class SingleFileComponentHotReloadHandlerEmitter
{
    /// <summary>The deterministic hint name for the consumer-assembly handler source.</summary>
    public const string HintName =
        "Viu.SingleFileComponentHotReloadMetadataUpdateHandler.g.cs";

    /// <summary>Emits the assembly attribute and conventional .NET Hot Reload forwarding methods.</summary>
    /// <returns>The generated C# source.</returns>
    public static string Emit()
        => """
            // <auto-generated/>
            #nullable enable

            [assembly: global::System.Reflection.Metadata.MetadataUpdateHandlerAttribute(
                typeof(global::Assimalign.Viu.Generated.SingleFileComponentHotReloadMetadataUpdateHandler))]

            namespace Assimalign.Viu.Generated
            {
                /// <summary>
                /// Forwards consumer-assembly metadata updates to Viu's component hot-reload runtime.
                /// </summary>
                internal static class SingleFileComponentHotReloadMetadataUpdateHandler
                {
                    /// <summary>
                    /// Deliberately preserves the previously recorded hashes for UpdateApplication to compare.
                    /// </summary>
                    /// <param name="updatedTypes">The types that may receive metadata updates.</param>
                    public static void ClearCache(global::System.Type[]? updatedTypes)
                    {
                    }

                    /// <summary>Applies updated component metadata after the runtime installs the delta.</summary>
                    /// <param name="updatedTypes">
                    /// The runtime's updated-type hint. Generated source edits can identify synthesized
                    /// implementation types instead of the mounted component, so Viu verifies every
                    /// registered component's content hashes.
                    /// </param>
                    public static void UpdateApplication(global::System.Type[]? updatedTypes)
                    {
                        global::Assimalign.Viu.ComponentHotReload.ApplyUpdates(updatedTypes);
                    }
                }
            }
            """;
}
