<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>$(TargetFrameworkForLibraries)</TargetFramework>
        <IsPackable>false</IsPackable>
    </PropertyGroup>
    <ItemGroup>
        <ViuPackageReference Include="Microsoft.NET.Test.Sdk" />
        <ViuPackageReference Include="xunit" />
        <ViuPackageReference Include="xunit.runner.visualstudio" />
        <ViuPackageReference Include="Shouldly" />
    </ItemGroup>
    <ItemGroup>
        <ViuPrivateProjectReference Include="Assimalign.Viu.Sdk.Browser.Tasks"
                                    ReferenceOutputAssembly="false"
                                    SkipGetTargetFrameworkProperties="true" />
    </ItemGroup>
</Project>
